### PR TITLE
publish - Correctly get information from prompt to update existing record

### LINKED ISSUE #9204: Updating a site published to Quarto Pub initiates first publish prompt
### Bug description

When using `quarto publish` to update a site already published to Quarto Pub, if I select the `Publish Update` option, instead of publishing, I get a prompt to select a publishing venue.

### Steps to reproduce

```bash
quarto create project website test-publish Test
cd test-publish
quarto publish quarto-pub
```
I select Quarto Pub and use my account details - site successfully publishes. 

`_publish.yml` looks like
```yml
- source: project
  quarto-pub:
    - id: 92bebd2d-14db-4ffd-9e78-48b62bdd1c1e
      url: 'https://charlotte.quarto.pub/test'
```

Then:
```bash
quarto publish
```

I get an option to update, but if I select it, it drop me back to the `Provider:` prompt.

### Expected behavior

Update should publish using existing settings in `_publish.yml`

### Actual behavior

The publish to a new source prompt is initiated:
```bash
posit/test-publish $ quarto publish 
? Publish update to: › https://charlotte.quarto.pub/test-publish (Quarto Pub - cwickham@gmail.com)
? Provider:
❯ Quarto Pub
  GitHub Pages
  Posit Connect
  Netlify
  Confluence
  Hugging Face Spaces
```

### Your environment

OS: Mac Sonoma 14.4

### Quarto check output

```bash
posit/test-publish $ quarto check
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.10.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
fatal: not a git repository (or any of the parent directories): .git
      Path: /Users/charlottewickham/Documents/posit/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.03.13
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/charlottewickham/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: /Users/charlottewickham/Documents/posit/quarto-web/.venv/bin/python
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```

### LINKED ISSUE #9228: quarto publish quarto-pub does not seem to be able to update a deployed document
Related to #9204 , updating a single file within a project seems not possible as it will round-trip to document creation 

````
❯ quarto publish quarto-pub index.qmd
? Publish update to: » https://examples.quarto.pub/collapsed-callout (Quarto Pub - quarto-examples@posit.co)
? Publish with account: » quarto-examples@posit.co
? Document name: » Use another name...
? Publish with name: » collapsed-callout
  The specified name is already in use within your account.
? Publish with name: »
ERROR: Error
    at promptForSlug (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/common/publish.ts:394:13)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async handlePublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/common/publish.ts:94:14)
    at async publishDocument (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/publish/publish.ts:310:36)
    at async publish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:276:9)
    at async doPublish (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:199:7)
    at async publishAction (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:252:7)
    at async Command.actionHandler (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/publish/cmd.ts:157:11)
    at async Command.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
````

- Example is already published
- `quarto publish` finds the existing url
- `quarto publish` wants to change name, and does not allow to reusing the same name. 

Not ideal behavior possibly linked... 
image

Document Name prompted will be used for the URL, but the title is not modified, and the one from the document name is used. 
It would have been better to have maybe a way to configure Title. 

Note that even using another name as `index.qmd` makes this problem happen.

### LINKED ISSUE #9764: quarto publish connect does not allow to update website and create new content
I believe something must have changed but currently publishing works but updating create new content. 

That is not good ! 

* Create a new website project
* Publish to a connect server with `quarto publish connect`
* Publishing works 
* Modify website, and call `quarto publish connect`, select the previous deploy
* It seems to work but content created is new. 

Also we document 
````
quarto publish connect --id <id to content> 
````

but it seems it does not work... 

Issue on our side or new stuff on connect that we don't account for ? 🤷‍♂️ 

cc @AshleyHenry15

### PR DESCRIPTION
**Pull request by cderv**
This PR correctly get prompt result for record to update

This should solve all our breakage with publish and update

- fixes #9764 
- fixes #9204
- fixes #9228

For the story, this is a breakage since 1.5.23 from an old PR (#8907) that we missed because we don't CI testing of `quarto publish` command, nor some Steps to follow for Manual testing to do when we modify these parts of the code base. 

Though this one would have been tricky because if needs prompt selection - so only manual testing would have help. 

I'll test the other provider before merging I'll do that next week.

### CODE REVIEW

**Comment by cderv** [comment]
Ok so after discussing with @gordonwoodhull, I tried to check everything on Ubuntu also; I can see the check issue locally, but still I see a problem with what we do. 

here is a minimal reproducible example with Deno 

````typescript
❯ ./package/dist/bin/tools/deno
Deno 1.41.0
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> import { Select } from "https://deno.land/x/cliffy@v1.0.0-rc.3/prompt/select.ts";
undefined
> const options=[{ name: "a", value: "b"}, {name: "c", value: "d"}];
undefined
> const confirm = await Select.prompt({
    indent: "",
    message: "Publish update to:",
    options,
  });
? Publish update to: › c
undefined
> confirm
"d"
````

This is replicating what we do, and so `confirm` is a `string`, not a `{ name: string, value: string}` object, as the type checking error says. 

So I am quite puzzled on this...

**Comment by cderv** [comment]
To confirm my understanding I went at the deno level. 

if I do this scripts `test.ts`

````typescript
import { Select } from "https://deno.land/x/cliffy@v1.0.0-rc.4/prompt/mod.ts";

const options=[{ name: "a", value: "b"}, {name: "c", value: "d"}];

const confirm = await Select.prompt({
    indent: "",
    message: "Publish update to:",
    options,
  });

if (confirm !== "d") {
  console.log("value is not d")
} else {
  console.log("value is d")
}

console.log(confirm)
````

and now run `deno run test.ts` it works ok

````bash
❯ deno run test.ts
? Publish update to: › a
value is not d
b
````

But if I check it that it errors 
````bash
❯ ~/project/quarto-cli/package/dist/bin/tools/deno check test.ts
Check file:///tmp/quarto/test.ts
error: TS2367 [ERROR]: This comparison appears to be unintentional because the types '{ name: string; value: string; }' and 'string' have no overlap.
if (confirm !== "d") {
    ~~~~~~~~~~~~~~~
    at file:///tmp/quarto/test.ts:11:5
````

If I modify to add the `confirm.value`

````typescript
import { Select } from "https://deno.land/x/cliffy@v1.0.0-rc.4/prompt/mod.ts";

const options=[{ name: "a", value: "b"}, {name: "c", value: "d"}];

const confirm = await Select.prompt({
    indent: "",
    message: "Publish update to:",
    options,
  });

if (confirm.value !== "d") {
  console.log("value is not d")
} else {
  console.log("value is d")
}

console.log(`confirm.value is ${confirm.value}`)
console.log(`confirm is: ${confirm}`)
````

it passes the checks but... we get wrong value

````bash
❯ deno run test.ts
? Publish update to: › c
value is not d
confirm.value is undefined
confirm is: d
````

So issue with cliffy and type checking or something I need to learn about how all this works ?

**Comment by gordonwoodhull** [comment]
I think that Typescript is inferring the wrong type for `Select.prompt()`and the error is spurious.

I think this is because `Select.prompt()` can take many different types for its `options`

https://deno.land/x/cliffy@v1.0.0-rc.1/prompt/select.ts?s=Select

In my not-very-informed opinion Typescript needs the nudge:

```typescript
const confirm = await Select.prompt<string>({
```

In practice the method always returns the value type, but here Typescript is inferring the `{name,value}` type wrongly.

So the update of `deployment.ts` in 396a8d was incorrect

```diff
-  if (confirm !== kOther) {
+  if (confirm.value !== kOther) {
     return depoyments.find((deployment) =>
-      publishRecordIdentifier(deployment.target, deployment.account) === confirm
+      publishRecordIdentifier(deployment.target, deployment.account) ===
+        confirm.value
     );
   } else {
     return undefined;
```

And we can't 100% trust Typescript errors when doing collateral evolution / API migration on an upgrade.

**Comment by cscheid** [comment]
> And we can't 100% trust Typescript errors when doing collateral evolution / API migration on an upgrade.

Just to add to this, Cliffy does a lot of really fancy type-level work, and has failed similarly in the past from one version upgrade to the next. You'll find a number of `any` sprinkled in our code base near the Cliffy commands because of things like this.

**Comment by gordonwoodhull** [comment]
This doesn’t explain why @cderv does not see the error in Windows. I hope that type inference is not platform-dependent!

**Comment by cderv** [comment]
Thanks a lot. I'll find a correct syntax that works everywhere, and try to understand why it does not fail on my side; I know what to do now. 

Looking through our code, I found other similar usage of `Select.prompt` that does not trigger a TypeCheck problem, while it is really exactly same usage (i.e. `options` is `{name: string, value: string}` and we compare than with results as string) 
https://github.com/quarto-dev/quarto-cli/blob/14c65d4cbccc79ed23c600668e822839e57b45f9/src/publish/common/publish.ts#L347-L366

So it may be related  on how the options are passed, and how their type is determined. Because modifying to this 
```diff
diff --git a/src/publish/common/publish.ts b/src/publish/common/publish.ts
index 2781b7e82..55d0b7deb 100644
--- a/src/publish/common/publish.ts
+++ b/src/publish/common/publish.ts
@@ -346,19 +346,20 @@ async function promptForSlug(
 
   if (await slugAvailable(slug)) {
     const kConfirmed = "confirmed";
+    const opts = [
+      {
+        name: slug,
+        value: kConfirmed,
+      },
+      {
+        name: "Use another name...",
+        value: "another",
+      },
+    ];
     const input = await Select.prompt({
       indent: "",
       message: `${typeName(type)} name:`,
-      options: [
-        {
-          name: slug,
-          value: kConfirmed,
-        },
-        {
-          name: "Use another name...",
-          value: "another",
-        },
-      ],
+      options: opts,
     });
     if (input === kConfirmed) {
       return slug;
```

gives me the error now
image

Good to know that cliffy can have this specific handling we need to managed !

**Pull request merged**
