### PR TITLE
omit output from divs with class 'comment'. Closes #696.

### LINKED ISSUE #696: [Feature Request] Special code blocks for comments
It would be useful to have something like [knitr's comment code block](https://github.com/yihui/knitr/releases/tag/v1.37) to leave comments that are not included in the output.

input

````qmd
---
title: test
format: commonmark
engine: knitr
---

<!-- comment (to be output) -->

```{comment}
not to be output
```
````

output

````md
<!-- comment (to be output) -->
````

(I noticed that the output file has no title.  I reported this bug in another issue. #697)

### PR DESCRIPTION
**Pull request by cscheid**

### CODE REVIEW

**Comment by cscheid** [comment]
@jjallaire this is new syntax so flagging it for your review. `comment` was the cleanest I could think of.

**Comment by jjallaire** [comment]
Let's consider whether we want this to actually prevent execution (as the knitr engine does). We should also consider whether the existing Pandoc comment syntax wouldn't be more suitable here.

**Comment by cooknl** [comment]
I just used the HTML comments `<!--` and `-->` and it worked great

**Comment by cscheid** [comment]
For our ongoing discussion: one issue with HTML comment syntax makes it necessary to be more careful when writing Lua filters, because the AST won't know in general whether or not a particular node is inside a comment.

**Comment by jjallaire** [comment]
A comment will actually turn the entire region into a raw HTML block so filters should be fine.

**Comment by jjallaire** [comment]
I'm going to close this for now pending further discussion of whether the HTML comment syntax is adequate for this purpose.

**Pull request closed without merging**
