### PR TITLE
Remove id on theorems Divs so that Pandoc does not insert raw Latex for us

### LINKED ISSUE #3776: Excessive vertical space before definition/theorem/etc environments in latex output.
### Bug description

There is excessive vertical space before definition/theorem/etc environments in latex output. 

Reproduce:
```
# Chapter

## Section

### Subsection

#### Subsubsection

Some text before the definition.

::: {#def-def}
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut purus elit,
vestibulum ut, placerat ac, adipiscing vitae, felis. Curabitur dictum gravida 
mauris.
:::

::: {#exm-exm}
Nam dui ligula, fringilla a, euismod sodales, sollicitudin vel, wisi. Morbi
auctor lorem non justo. Nam lacus libero, pretium at, lobortis vitae, ultricies et, tellus.
:::

Some text before the theorem.

::: {#thm-thm}
Nulla malesuada porttitor diam. Donec felis erat, congue non, volutpat
at, tincidunt tristique, libero. Vivamus viverra fermentum felis.
:::
::: {.proof}
Quisque ullamcorper placerat ipsum. Cras nibh. Morbi vel justo vitae lacus
tincidunt ultrices. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
In hac habitasse platea dictumst.
:::

Some text afterwards.
```
Quarto configuration is the standard when creating a new quarto project in RStudio. So, the latex class is set as `documentclass: scrreprt`. However, the issue is noticeable in other classes.

Pdf render where the amount of inter space can be appreciated:
image

Compare with the hand written latex version using same class:
image

Examining the generated tex file i see every definition (and similar) environment is prepended with some extra code. For example, for the definition we have:

```
Some text before the definition.

\leavevmode\vadjust pre{\hypertarget{def-def}{}}%
\begin{definition}[]\label{def-def}

Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut purus elit,
vestibulum ut, placerat ac, adipiscing vitae, felis. Curabitur dictum
gravida mauris.

\end{definition}
```
I don't know what is the purpose of `\leavevmode\vadjust pre{\hypertarget{def-def}{}}` but it is adding unwanted vertical space. In fact, removing it solves the issue.

But there is another thing not related to aforementioned extra code. Note the height where the proof QED symbol (the white box) is placed. In the quarto version is below normal position. From my tests, i see that an empty line between the end of the proof text and the end proof tag makes a difference. That is, quarto generates the proof as follows:

```
\begin{proof}

Quisque ullamcorper placerat ipsum. Cras nibh. Morbi vel justo vitae
lacus tincidunt ultrices. Lorem ipsum dolor sit amet, consectetuer
adipiscing elit. In hac habitasse platea dictumst.

\end{proof}
```

But if we just remove the final empty line to have:

```
\begin{proof}

Quisque ullamcorper placerat ipsum. Cras nibh. Morbi vel justo vitae
lacus tincidunt ultrices. Lorem ipsum dolor sit amet, consectetuer
adipiscing elit. In hac habitasse platea dictumst.
\end{proof}
```

then the QED symbol goes up where we expect it to be.

More info:

- Quarto 1.2.280
- R studio 2022.12.0 Build 353
- Windows 11 Pro 22H2

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

### PR DESCRIPTION
**Pull request by cderv**
fixes #3776 

<details>
<summary>Qmd document to test this </summary>

````markdown
---
title: "My Document"
format: 
  pdf:
    keep-tex: true
    number-sections: true
---

# Chapter

## Section

### Subsection

#### Subsubsection

Some text before the definition.

::: {#def-def}
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut purus elit,
vestibulum ut, placerat ac, adipiscing vitae, felis. Curabitur dictum gravida 
mauris.
:::

::: {#exm-exm}
Nam dui ligula, fringilla a, euismod sodales, sollicitudin vel, wisi. Morbi
auctor lorem non justo. Nam lacus libero, pretium at, lobortis vitae, ultricies et, tellus.
:::

Some text before the theorem.

::: {#thm-thm}
Nulla malesuada porttitor diam. Donec felis erat, congue non, volutpat
at, tincidunt tristique, libero. Vivamus viverra fermentum felis.
:::
::: {.proof}
Quisque ullamcorper placerat ipsum. Cras nibh. Morbi vel justo vitae lacus
tincidunt ultrices. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
In hac habitasse platea dictumst.
:::

Some text afterwards. Next see @thm-thm

````

</details>

With this, we don't get the insertion of 
````latex
\leavevmode\vadjust pre{\hypertarget{def-def}{}}%
````
before our theorems blocks

Ideally we may need to add a `\protect\hypertarget` call back in there, but I don't for what it used in this case. Is this needed ? 

Opening this as a draft now to trigger tests.

### CODE REVIEW

**Comment by cscheid** [comment]
Hm - I don't know enough LaTeX internals to be able to review this confidently.

Removing that id is something to be careful about, because we use IDs for crossrefs, etc. We should explicitly check we have tests that cover whatever id is being removed.

**Comment by cderv** [comment]
> Hm - I don't know enough LaTeX internals to be able to review this confidently.

There no much LaTeX change here. Removing the id on the div makes Pandoc not insert the raw latex, so we add our own, and this is what we do in **bookdown**. This LaTeX is valid. 

Your feedback on crossref and tests is much valuable to me as I don't know the internals well, and no so used to the test organization we have. 

## What I checked 

We are already in the crossref filters part and it seems to me we are getting the id already in 
https://github.com/quarto-dev/quarto-cli/blob/f7fce46f348aeadb7fa902e3ca88568a27158f45/src/resources/filters/crossref/theorems.lua#L47-L50
Isn't that enough for our crossref system ? I don't know the internals well enough. Removing it after collecting seemed enough. 
In HTML it would have some impact, but it LaTeX, a Div gives nothing really in LaTeX raw code. 

Regarding test, our current one are passing so I am assuming that our crossref tests are ok: The `@thm-thm` will be resolved as we test in https://github.com/quarto-dev/quarto-cli/blob/main/tests/smoke/crossref/thereoms.test.ts

This means to me that the referencing still works even without the id. To be clear : We are removing an id only for Theorems type block after the id being collected and only for LaTeX output. 

> We should explicitly check we have tests that cover whatever id is being removed.

Do you have other checks in mind for this change ? Or what type of tests are you thinking about ? 
I would need some help to know how and where to add more tests if needed. 

I added as reviewer as you were assigned before me on the issue, but if anyone knows better about crossref, happy to bring the topic so someone else .

**Comment by cscheid** [comment]
> We are already in the crossref filters part and it seems to me we are getting the id already in
> Isn't that enough for our crossref system ? I don't know the internals well enough. Removing it after collecting seemed enough.

It might be! I asked simply because I don't know if your change causes us to go through that code path. It might be! but I would like to make sure it does before we introduce a change that isn't covered in the test suite.

> Regarding test, our current one are passing so I am assuming that our crossref tests are ok: The @thm-thm will be resolved as we test in https://github.com/quarto-dev/quarto-cli/blob/main/tests/smoke/crossref/thereoms.test.ts

That's good, but the reason I asked was to make sure that whatever id was getting removed behaves correctly. What I'm not sure is that we actually have a test that exercises this case.

> Do you have other checks in mind for this change ? Or what type of tests are you thinking about ?

Not at the top of my head. But I would try to write a .qmd file that has an ID which gets "deleted" by your code path, and at the same time is still referenceable with a crossref. This would indicate that the removal of the ID caused our `[theorems.lua](https://github.com/quarto-dev/quarto-cli/blob/f7fce46f348aeadb7fa902e3ca88568a27158f45/src/resources/filters/crossref/theorems.lua#L47-L50)` codebase to trigger correctly.

**Comment by cderv** [comment]
Thanks for explaining. 

I'll add a test for PDF outputs even if we don't do much as it is LaTeX resolves the referencing. Navigating through the code it seems we at least replace `@` by `\ref` by tweaking the `Cite` element, based on our index of crossrefs. So I'll add a test for that.  

Is adding to https://github.com/quarto-dev/quarto-cli/blob/main/tests/smoke/crossref/thereoms.test.ts is still fine, as I did a few times before ? 
Or should I use a new way of adding test (for which I would need a few pointers) ?

**Comment by cderv** [comment]
I was going to add a newt test for LaTeX, but in fact I believe it is already there in `all.qmd`

https://github.com/quarto-dev/quarto-cli/blob/6a42abc996a7807d7a3538dcea835a11174fe13e/tests/docs/crossrefs/all.qmd#L62-L74

https://github.com/quarto-dev/quarto-cli/blob/e5687371f5c6a3e80d761577c2ee406b65706ff0/tests/smoke/crossref/latex.test.ts#L34-L47

I believe this test insure that the id for the theorem div is correctly retrieved and handled by our system in 
https://github.com/quarto-dev/quarto-cli/blob/c1efe2579660a88f2db6ee4d36faf4f661d136f5/src/resources/filters/crossref/refs.lua#L24

However I adapted the test to check that we correctly handle the modification for `leavevmode` and `hypertarget`

**Comment by cscheid** [comment]
Ok, this looks good to me. Thank you!

**Comment by cscheid** [comment]
Can you add an entry to the changelog? Other, this looks good to me!

**Comment by cderv** [comment]
All good then I think. 

- Changes made
- Changelog updated
- Tests are passing

Just to get back completely in the process we should have: 

* Do you expect me to merge now myself that you have reviewed with LGTM in your last comment ?  

Asking because it is not a formal "Github PR approval"  with green check ✅ ... don't want to misinterpret 😅   
And not sure if anyone of us is supposed to merge or just you and @dragonstyle - I don't want to mess with any `main` usage I missed or  any specific inclusion regarding pre-release build. 

Anyway, just asking and I'll capture this in our handbook maybe so any developer in the team know how to make PR in coordination with a Tech lead. (cc @allenmanning )

**Review by cscheid — APPROVED** [review]
This LGTM but I would be more comfortable with @dragonstyle took a look as well.

**Comment by dragonstyle** [comment]
LGTM too! merging...

**Pull request merged**
