### PR TITLE
Modify the path depending on VSCODE_PROXY_URI

### LINKED ISSUE #3227: Don'

### PR DESCRIPTION
**Pull request by benz0li**
## Description

#3228 did not work as expected.

Closes #3227.

## Checklist

I have (if applicable):

- [ ] filed a [contributor agreement](../CONTRIBUTING.md).
- [x] referenced the GitHub issue this PR closes
- [x] updated the appropriate changelog

### CODE REVIEW

**Comment by cscheid** [comment]
Ok, thanks for the new PR. We need to take a closer look to try and minimize regressions and churn here.

**Comment by jjallaire** [comment]
@cscheid and @dragonstyle I think we should take this one for v1.2 (and produce another build of it)

**Comment by jjallaire** [comment]
@benz0li  Will this work for both older and newer versions of code server? (we don't want to break people that haven't yet updated)

**Comment by benz0li** [comment]
> @benz0li Will this work for both older and newer versions of code server? (we don't want to break people that haven't yet updated)

@jjallaire I have updated the code. Now it does work for both older and newer versions of code server.

**Comment by benz0li** [comment]
> @cscheid and @dragonstyle I think we should take this one for v1.2 (and produce another build of it)

That would be great. Thank you!

**Comment by jjallaire** [comment]
@cscheid and @dragonstyle I think once we take this on `main` we should tag it as a "patch release" issue for back porting (i.e. don't force a re-release of v1.2 but rather queue it up for inclusion when we do finally release a patch).

@benz0li You'll still be able to get this fix in our v1.3 pre-release binaries once we merge it.

**Pull request merged**
