### PR TITLE
Language support for Basque

### PR DESCRIPTION
**Pull request by iagobaapellaniz**
Couple of questions regarding the agreement

- Can I fill the form and sign it digitally?
- Do I have to fill all the fields?
- What "Facsimile" stands for? Can I leave as it is?

## Checklist

I have (if applicable):

- [x] filed a [contributor agreement](https://github.com/quarto-dev/quarto-cli/blob/main/CONTRIBUTING.md).
- [x] updated the appropriate changelog in the PR

### CODE REVIEW

**Comment by cscheid** [comment]
> * Can I fill the form and sign it digitally?
Yes.

> * Do I have to fill all the fields?
Fill every one for which you have an answer (name/email/phone number are required)

> * What "Facsimile" stands for? Can I leave as it is?
That's a fax number. Yes, you can leave it unfilled if you don't have one.

**Comment by iagobaapellaniz** [comment]
I confirm I sent the agreement. Thanks

**Comment by cscheid** [comment]
Thanks! But I don't see an change in our changelog. Could you please do that?

**Comment by iagobaapellaniz** [comment]
Sorry, since I red "appropriate changelog", I just updated the readme file in languages. I'll do it soon.

**Comment by iagobaapellaniz** [comment]
Done! I also fixed a brroken link in changelog

**Comment by cscheid** [comment]
Thank you!

**Pull request merged**
