### PR TITLE
deno - replace deprecated Deno.run with Deno.Command

### LINKED ISSUE #8891: Replace Deno.run with Deno.command
### Bug description

Deno.run is deprecated and Deno recommends using Deno.command instead: https://docs.deno.com/runtime/manual/advanced/migrate_deprecations#denorun 

This was discovered while I was writing automation for Workbench that used Quarto. Using `deno.run` exposes quarto to this bug: https://github.com/denoland/deno/issues/7087#issuecomment-1483292727 which prevents us from being able to run quarto through pytest in Jenkins. 

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Actual behavior

_No response_

### Your environment

_No response_

### Quarto check output

_No response_

### PR DESCRIPTION
**Pull request by cscheid**
Closes #8891.

### CODE REVIEW

**Comment by cscheid** [comment]
This is a bit obnoxious. Using Deno.Command crashes `command.output()` with a failed assertion deep into the Deno runtime:

```
Stack trace:
    at assert (ext:deno_web/00_infra.js:374:11)
    at readableStreamError (ext:deno_web/06_streams.js:2479:3)
    at readableStreamCollectIntoUint8Array (ext:deno_web/06_streams.js:1039:7)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Promise.all (index 1)
    at async ChildProcess.output (ext:runtime/40_process.js:295:49)
    at async execProcess (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/core/process.ts:175:20)
    at async pandocListFormats (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/core/pandoc/pandoc-formats.ts:17:18)
```

(The CI output doesn't show this stack trace, I obtained it locally)

**Comment by cscheid** [comment]
We're blocked here until we upgrade Deno, I think.

But we're blocked on upgrading Deno until we confirm that the fix for https://github.com/denoland/deno/issues/22180 has landed and resolves our issues.

**Comment by cscheid** [comment]
This PR is currently blocked by a Deno v1.41.0 bug with the following repro:

### deno_repro.ts

```ts
async function processOutput(iterator: AsyncIterable<Uint8Array>): Promise<string> {
  const decoder = new TextDecoder();
  let outputText = "";
  for await (const chunk of iterator) {
    const text = decoder.decode(chunk);
    outputText += text;
  }
  return outputText;
}

async function* iteratorFromStream(stream: ReadableStream<Uint8Array>) {
  const reader = stream.getReader();
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) return;
      yield value;
    }
  } finally {
    reader.releaseLock();
  }
}

const command = new Deno.Command("ls", {stdout: "piped", stderr: "piped"});
const process = command.spawn();

const promises: Promise<unknown>[] = [
  processOutput(iteratorFromStream(process.stdout)),
  processOutput(iteratorFromStream(process.stderr)),
];

await Promise.all(promises);

// assertion fails here
const status = await process.output();
```

```
$ deno run --allow-all deno_repro.ts
error: Uncaught (in promise) AssertionError: Assertion failed.
const status = await process.output();
               ^
    at assert (ext:deno_web/00_infra.js:374:11)
    at readableStreamError (ext:deno_web/06_streams.js:2529:3)
    at readableStreamCollectIntoUint8Array (ext:deno_web/06_streams.js:1081:7)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async Promise.all (index 1)
    at async ChildProcess.output (ext:runtime/40_process.js:322:49)
    at async file:///Users/cscheid/Desktop/daily-log/2024/02/28/deno_repro.ts:35:16
```

**Comment by cscheid** [comment]
Upstream deno bug report: https://github.com/denoland/deno/issues/22621

**Comment by lucacasonato** [comment]
We're fixing the upstream bug now, but you can unblock yourself here by using `child.status` instead of `child.output()`. `child.status` just waits for the process to exit, while `child.output()` also tries to consume `stdout` and `stderr` until EOF, which is not necessary in your case, because you do that yourself already.

**Pull request closed without merging**
