### PR TITLE
pptx - add a cleanup finalize step to remove RawBlock different from openxml

### LINKED ISSUE #9680: Slides wth computed HTML table and a title are inserted using two column layout instead of Title and content
I have tested the fix for #9365 using quarto 1.5.36 and it works in the sense that HTML tables are now displayed but they are getting inserted in the top right corner instead of in the "body" of the pptx layout as it was the case before. This implies manual post-processing of the presentation wich defeats the purpose of automation.

_Originally posted by @andresrcs in https://github.com/quarto-dev/quarto-cli/issues/9365#issuecomment-2112666797_

### LINKED ISSUE #9681: Empty slide created for parsed HTML tables in powerpoint
Found while looking at #9680 

````markdown
---
title: "Test"
format: pptx
keep-md: true
---

## Test Table

```{r}
#| label: test

head(iris, 1) |>  
    knitr::kable(format = "html")
```

## Test Table

```{r}
#| label: test

head(iris, 1) |>  
    knitr::kable(format = "pipe")
```

````

image

<details>
<summary>Intermediate md</summary>

````markdown
---
title: "Test"
format: pptx
keep-md: true
---




## Test Table



::: {.cell}
::: {.cell-output-display}

`````{=html}
<table>
 <thead>
  <tr>
   <th style="text-align:right;"> Sepal.Length </th>
   <th style="text-align:right;"> Sepal.Width </th>
   <th style="text-align:right;"> Petal.Length </th>
   <th style="text-align:right;"> Petal.Width </th>
   <th style="text-align:left;"> Species </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 5.1 </td>
   <td style="text-align:right;"> 3.5 </td>
   <td style="text-align:right;"> 1.4 </td>
   <td style="text-align:right;"> 0.2 </td>
   <td style="text-align:left;"> setosa </td>
  </tr>
</tbody>
</table>

`````

:::
:::

## Test Table

::: {.cell}
::: {.cell-output-display}

| Sepal.Length| Sepal.Width| Petal.Length| Petal.Width|Species |
|------------:|-----------:|------------:|-----------:|:-------|
|          5.1|         3.5|          1.4|         0.2|setosa  |

:::
:::

````

</details>

### PR DESCRIPTION
**Pull request by cderv**
Pandoc may have an issue in its writer as, like other formats it will correctly ignore other format RawBlock, but it seems to mess the created pptx file (e.g. choosing the wrong layout, creating empty new slides)

We add those raw blocks in some places like HTML table parsing 

This fix #9680  and fix #9681 - some details can be found in each of those issue. 

This PR is too discussed the idea of doing such cleanup step. 

Other solution I had in mind would be to adapt the HTML processing step so that it adds the HTML RawBlock only for HTML format. This would be more generic but usually Pandoc does a good job to ignore RawBlock for a different format in the Writers.

Opening as Draft to discuss this.  Tests needs to be added too.

### CODE REVIEW

**Comment by cscheid** [comment]
Can this filter become `post-render-pptx-fixups`? We have a number of these in `quarto_post_filters`.

**Comment by cderv** [comment]
> Can this filter become `post-render-pptx-fixups`? We have a number of these in `quarto_post_filters`.

yes definitely - I associated this with Cleanup that seemed to be in finalized, but I can definitely do that in post render. 

Let's see if this works.

**Comment by cderv** [comment]
And now new function to verify the maximum number of slides we expect in a presentation

**Comment by cderv** [comment]
@cscheid this PR is ready.  

better with post-render step ?

**Comment by cscheid** [comment]
Great!

**Pull request merged**
