### PR TITLE
Parsed HTML table wrapping div needs to be scaffold so that it is removed

### LINKED ISSUE #9365: HTML tables are no more rendered in PPTX output
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/9363

<div type='discussions-op-text'>

<sup>Originally posted by **andresrcs** April 13, 2024</sup>
### Description

I used to be able to insert `gt` tables in PowerPoint presentations seamlessly but It has stopped working, here you can find a minimal reproducible example. If you render this code, it produces a presentation with no table in it.

I'm using `quarto` version 1.4.553 that comes bundled with RStudio (daily build 2024.04.0 Build 693)

````qmd
---
title: "Test"
format: pptx
editor: visual
---

```{r setup}
library(gt)
```

## Test Table

```{r}
#|label: test

iris %>% 
    gt() %>%
    as_raw_html()

```
````</div>

### PR DESCRIPTION
**Pull request by cderv**
Especially because powerpoint does not allow Div and Tables in DivWelcome to the quarto GitHub repo!

fixes #9365

### CODE REVIEW

**Comment by cderv** [comment]
@cscheid I labelled #9365 has regression because it was working with 1.3. 

Is this ok to backport this change to you ?

**Comment by gordonwoodhull** [comment]
This also fixes #8797

**Comment by cscheid** [comment]
Yes, let's backport it.

**Comment by cscheid** [comment]
Will this also close https://github.com/quarto-dev/quarto-cli/issues/6529?

**Comment by cderv** [comment]
> This also fixes #8797

Thanks @gordonwoodhull. I commented at https://github.com/quarto-dev/quarto-cli/issues/8797#issuecomment-2109702988. I think this is fixed by prerelease already for what is reported. Though I added a test for typst here, because parsed HTML table where also an issue leading to aligned table. It seems center align is our default for Typst in 1.5.

**Comment by cderv** [comment]
> Will this also close #6529?

@cscheid unfortunately no. I believe #6529 is related to processing of FloatRefTarget in PPTX being limited. I'll comment there and dig more.

**Comment by cderv** [comment]
This was backported in 1.4 for next patch release, and changelog added there. Merging this in main now.

**Pull request merged**
