### PR TITLE
Correct redirect for code-server

### LINKED ISSUE #3352: Render PDF: 'Open in Browser' opens wrong link (code-server with Jupyter Server Proxy)
### Bug description

render-pdf_open-in-browser

'Open in Browser' opens https://coder.jupyter.b-data.ch/hub/proxy/7095/web/viewer.html, which is wrong.

---

render-pdf_browse-at

Browse at shows https://coder.jupyter.b-data.ch/user/benz0li/code-server/proxy/7095/web/viewer.html, which is correct.

---

@jjallaire @cscheid @dragonstyle May be reproduced at https://coder.jupyter.b-data.ch with image `R (jupyterlab/r/verse:latest-devtools)` using

````qmd
---
title: "ggplot2 demo"
author: "Norah Jones"
date: "5/22/2021"
format: 
  html:
    code-fold: true
    fig-format: svg
---

## Air Quality

@fig-airquality further explores the impact of temperature on ozone level.

```{r}
#| label: fig-airquality
#| fig-cap: Temperature and ozone level.
#| warning: false

library(ggplot2)

ggplot(airquality, aes(Temp, Ozone)) + 
  geom_point() + 
  geom_smooth(method = "loess"
)
```
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

### PR DESCRIPTION
**Pull request by benz0li**
## Description

Closes #3352

## Checklist

I have (if applicable):

- [ ] filed a [contributor agreement](../CONTRIBUTING.md).
- [x] referenced the GitHub issue this PR closes
- [x] updated the appropriate changelog

### CODE REVIEW

**Comment by cscheid** [comment]
@benz0li Thanks for the contribution!

**Comment by benz0li** [comment]
@cscheid Unfortunately, this has net been backported to v1.2 and is therefore missing in v1.2.280.

**Comment by cscheid** [comment]
@benz0li We tend to be _very_ conservative about backports (because they're included on other Posit products), so that was very likely by design.

@jjallaire Should we consider a backport of this one?

**Comment by jjallaire** [comment]
Our plan was certainly to backport it (in fact it's worth another check to make sure we didn't!). If we haven't backported it we should

**Comment by cscheid** [comment]
@jjallaire ok, great. I missed that. I'll check and put together a backport PR today.

**Pull request merged**
