### PR TITLE
Bahasa Indonesia (id) translation

### PR DESCRIPTION
**Pull request by mohammadrizki**
*add Bahasa Indonesia (id) translation

## Description

Please describe your PR here.

````md
```py
print("Add Bahasa Indonesia (id) translation")
```
````

## Checklist

I have (if applicable):

- [x] filed a [contributor agreement](../CONTRIBUTING.md).
- [ ] referenced the GitHub issue this PR closes
- [ ] updated the appropriate changelog

### CODE REVIEW

**Comment by dragonstyle** [comment]
Thank you!

We have added one additional string for `section-title-copyright: "Copyright"` to the primary language file. Would it be possible for you to provide a translation for this as well?

**Comment by mohammadrizki** [comment]
Sure. I've updated the translation.

**Comment by dragonstyle** [comment]
Thank you!

**Comment by cscheid** [comment]
Thank you!

**Pull request merged**
