### PR TITLE
Correctly detect a global sidebar and not a specific page sidebar

### LINKED ISSUE #9242: Sidebar not displayed if no Quarto document
The sidebar is not displayed if it does not include a Quarto document even-though there is content such as external links.

<table>
<tr><th>Sidebar displayed</th><th>Sidebar not displayed</th></tr>
<tr><td>

````qmd
project:
  type: website

website:
  title: "Test"
  page-navigation: true
  navbar:
    left:
      - text: "External working"
        href: "https://quarto.org"
        target: "_blank"

  sidebar:
    - title: "Dropdown"
      contents:
        - text: "External working"
          href: "https://quarto.org"
          target: "_blank"
        - index.qmd

format:
    html: default
````

</td><td>

````qmd
project:
  type: website

website:
  title: "Test"
  page-navigation: true
  navbar:
    left:
      - text: "External working"
        href: "https://quarto.org"
        target: "_blank"

  sidebar:
    - title: "Dropdown"
      contents:
        - text: "External working"
          href: "https://quarto.org"
          target: "_blank"

format:
    html: default
````

</td></tr>
</table>

_Originally posted by @mcanouil in https://github.com/quarto-dev/quarto-cli/issues/9153#issuecomment-2029528267_

### LINKED ISSUE #9728: Sidebar not loading properly in new version, works in old version
### Bug description

image
When rendering my site with the new version of Quarto, v1.4.554, the sidebar does not load in and the darkmode toggle ends up way up in the top right for some reason. If I downgrade to v1.3.450 it works as expected again.
image

### Steps to reproduce

I'm not sure what to share here, as all I'm doing is switching quarto versions and re-rendering. Here's my _quarto.yaml though.
```project:
  output-dir: docs
  type: website
  render:
    - "*.qmd"
    - "!old/"

format:
  html:
    number-sections: false
    toc: true
    theme:
      light: custom-light.scss
      dark: custom-dark.scss
    #  pdf: #how do I make this all go into the same pdf instead of multiple files? Is that the "book" "type" setting in "project"?? This is poorly documented...
    #    number-sections: true
  pdf:
    latex-auto-install: true
    #documentclass: "scrbook"
    # tbl-colwidths: true # need to instead just specify spacing for specific tables
    fontfamily: libertinus
    geometry:
      - nomarginpar
      - top=0.5in
      - bottom=0.5in
      - outer=0.5in
      - inner=0.5in
    number-sections: false
    toc: false

website:
  title: "citatel"
  repo-url: https://github.com/ikolith/citatel
  favicon: "./assets/images/favicons/favicon.ico"
  page-navigation: true

  sidebar:
    id: "sidebarid"
    openSidebar: true
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - section: "About"
        contents:
          - book/about/mutiny.qmd
          #- book/about/about.qmd
      - section: "Rules"
        contents:
          - book/rules.qmd
      - section: "Skills, Weapons, Items"
        contents:
          - book/stuff/basic.qmd
          - book/stuff/spoilers.qmd
      # - section: "Menagerie"
      #   contents: "book/menagerie/*.qmd"
```

### Expected behavior

Sidebar should show up in when rendering to website.

### Actual behavior

Sidebar does not show up.

### Your environment

Using VSCode, but the same thing happens from the command line. Using MacOS Sonoma 14.3.1.

### Quarto check output

Old working version:
```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /Users/ibex/shed/citatel/.venv/bin/python
      Jupyter: 5.6.1
      Kernels: mojo-jupyter-kernel, python3

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

(.venv)
 ```

Newer version:

``` 
Quarto 1.4.554
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.554
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /Users/ibex/shed/citatel/.venv/bin/python
      Jupyter: 5.6.1
      Kernels: mojo-jupyter-kernel, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

(.venv)
 ```

Pre-Release! Also broken!

```
Quarto 1.5.37
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.37
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /Users/ibex/shed/citatel/.venv/bin/python
      Jupyter: 5.6.1
      Kernels: mojo-jupyter-kernel, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

(.venv) 
```

### PR DESCRIPTION
**Pull request by cderv**
global sidebard is detected by `undefined` id, so we need to compute id from title not too early, and in a a way that does not modify initial config

Closes #9242 and closes #9728

----

This is currently a proposal built on top of unmerged https://github.com/quarto-dev/quarto-cli/pull/8871 by @dragonstyle to deal with #8869 and follow up on #5689

I believe we can do what was supposed to be done in #8871, but we need to make sure that we don't modify initial `navigation.sidebars` content's id. 

I still think we could consider adding a more explicit `global` config for `true` or `false` to make this more clear. 

This requires some testing to be sure it works ok this time. Opening this draft PR to discuss and have thoughts on this change.

### CODE REVIEW

**Comment by ikolith** [comment]
> global sidebard is detected by `undefined` id, so we need to compute id from title not too early, and in a a way that does not modify initial config
> 
> Closes #9242 and closes #9728
> 
> This is currently a proposal built on top of unmerged #8871 by @dragonstyle to deal with #8869 and follow up on #5689
> 
> I believe we can do what was supposed to be done in #8871, but we need to make sure that we don't modify initial `navigation.sidebars` content's id.
> 
> I still think we could consider adding a more explicit `global` config for `true` or `false` to make this more clear.
> 
> This requires some testing to be sure it works ok this time. Opening this draft PR to discuss and have thoughts on this change.

I removed the sidebar id and this did work, thanks! Looking forward to whatever changes would make this clearer.

**Comment by cscheid** [comment]
@cderv Before we merge this, can you add a regression test?

**Comment by cderv** [comment]
Oh sure. My bad. I believe we can run project tests now.

**Comment by cderv** [comment]
I reverted this PR in 4ee3e32ca9f3f920f408ea1973beed528170f34b because it broke quarto-web. 
I'll reopen the linked issue, and deal with this in 1.6 so sort out this change in sidebar processing.

**Pull request merged**
