### PR TITLE
Chore/pandoc 3.1.13

### PR DESCRIPTION
**Pull request by gordonwoodhull**
Opening a pull request for this because

* I think we want to merge this now for Typst 0.11 support.
* We don't know if we will want to update Pandoc again for 1.5, better not to wait.
* @cscheid fixed most of the failures but it looks like there is one left <strike>(equally obscure to me, but I'm new here)</strike>

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
This failure looked similar so I did a similar change, let's see if everything passes now.

```diff
   local latex_caption
   if float.caption_long and type(float.caption_long) ~= "table" then
     latex_caption = quarto.utils.as_inlines(float.caption_long)
   else
     latex_caption = float.caption_long
   end
+  latex_caption = latex_caption or pandoc.Inlines({})

   if #latex_caption == 0 then
```

**Comment by gordonwoodhull** [comment]
Hmm, we also have to merge templates before we can merge this, let's go over that tomorrow.

**Comment by cscheid** [comment]
That looks correct to me!

**Comment by cscheid** [comment]
Tests pass, great. Before we merge, let me check for template changes.

**Comment by gordonwoodhull** [comment]
I already made the Typst template change; the file has been renamed to `typst-template.typ`

Fixed and will squash before merging if we're all good on templates?

**Comment by gordonwoodhull** [comment]
Ugh, I was wrong about the renamed file - it was renamed under `formats/typst/pandoc/quarto` not `formats/typst/pandoc`

So we have
* `formats/typst/pandoc/typst.template`
* `formats/typst/pandoc/template.typst` -> same as `pandoc/data/templates/template.typst
* `formats/typst/pandoc/quarto/template.typ`
* `formats/typst/pandoc/quarto/typst-template.typ`

I modified the last one some weeks ago, and it had the desired effect (as seen by #9286 😉).

AFAICT none of these files have comparable content.

`formats/typst/pandoc/typst.template` _has_ received regular updates with Pandoc. However
* The tests all passed with this file deleted.
* Making the desired change (removing gridlines) has no effect when applied here.
* The only reference to this filename I find in the sources is in `quarto-cli/package/src/common/update-pandoc.ts` (and I think that's in a different path).

So what's going on here?

**Pull request closed without merging**
