### PR TITLE
fix: Add missing CC licences and display CC code instead of URL

### LINKED ISSUE #6783: Add more CC licences
It seems to be a good/simple enhancement.

Note that PRs are always welcome and in this case, it seems straightforward for you to contribute if you feel like it: 
- https://github.com/quarto-dev/quarto-cli/blob/f87976c6dc9b0d0ea125ac58ad08860d63dae8ad/src/format/html/format-html-appendix.ts#L39-L45
- https://github.com/quarto-dev/quarto-cli/blob/f87976c6dc9b0d0ea125ac58ad08860d63dae8ad/src/resources/filters/modules/license.lua#L11-L49
- https://github.com/quarto-dev/quarto-cli/blob/f87976c6dc9b0d0ea125ac58ad08860d63dae8ad/src/resources/schema/document-metadata.yml#L49-L73

---

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/6770

<div type='discussions-op-text'>

<sup>Originally posted by **the-solipsist** September  8, 2023</sup>
### Description

1. Currently only the following four Creative Commons licences are supported:
    1. CC BY
    2. CC BY-SA
    3. CC BY-ND
    4. CC BY-NC
   
   This means that licences such as CC BY-NC-SA are not supported. It's not clear why, given that the code to support all the CC licences won't add any complexity.

2. If `licence:` metadata is CC BY-NC, and the language is en-IN, then it generates a link to https://creativecommons.org/licenses/by-nc/4.0/deed.en-in (with that URL as the text).

   It would be preferable to use [Creative Commons badges or icons](https://creativecommons.org/about/downloads/), with the appropriate URL instead. Or at the very least, to use the licence short code as the anchor text for the link.  Even better would be to generate text + machine-readable code instead of just a bare URL, but this might run into internationalization issues.

`<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons License</a><br /><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Text" property="dct:title" rel="dct:type">A pantent conundrum</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://indianexpress.com/article/opinion/columns/a-patent-conundrum/" property="cc:attributionName" rel="cc:attributionURL">Pranesh Prakash</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.`
rather than
`<section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div id="quarto-reuse" class="quarto-appendix-contents"><div><a rel="license" href="[https://creativecommons.org/licenses/by-nc/4.0/deed.en_in](view-source:https://creativecommons.org/licenses/by-nc/4.0/deed.en_in)">https://creativecommons.org/licenses/by-nc/4.0/deed.en_in</a></div></div></section>`</div>

### PR DESCRIPTION
**Pull request by mcanouil**
This PR add the missing CC licenses and also use the CC code as display test instead of the license URL.

image

Fixes #6783

### CODE REVIEW

**Comment by cderv** [comment]
Just a note that this has been addressed in https://github.com/quarto-dev/quarto-cli/commit/9b817de623a877fb1db3c2a3279e9bb2c86c0df2 already, hence the merge conflict.

**Comment by mcanouil** [comment]
@dragonstyle and I are aware since we did it at the same time (although I assigned myself the issue first to let others know 😅)

**Comment by cderv** [comment]
Ok good. Though it is hard to review a PR that has a conflict. So I wasn't sure you had seen the commit in main, and the conflict. 

Wouldn't it be better to fix the PR here to remove conflict to clearly show the proposed changed ? 
Probably either 
* revert https://github.com/quarto-dev/quarto-cli/commit/9b817de623a877fb1db3c2a3279e9bb2c86c0df2 and keep all this change, 
* Or adapt https://github.com/quarto-dev/quarto-cli/commit/9b817de623a877fb1db3c2a3279e9bb2c86c0df2 with your specific idea. 

Anyhow, I let you deal with that. It is just conflict in PR usually means hard to review and even no-go for review sometimes.

**Comment by mcanouil** [comment]
I fixed the conflict and updated the code to display the license instead or the URL as in my screenshot.

**Comment by dragonstyle** [comment]
This is a very nice improvement, sorry again for the conflict!

**Review by dragonstyle — APPROVED** [review]

**Pull request merged**
