### PR TITLE
document rendering needs to check quarto-required not quarto-version

### LINKED ISSUE #6071: quarto-required argument is ignored
### Bug description

Using the `quarto-required` argument as described here: https://quarto.org/docs/reference/formats/html.html#format-options doesn't appear to work.

### Steps to reproduce

````qmd
---
format:
  html:
    quarto-required: ">= 1000.4.375"
---

## Quarto

````

### Expected behavior

I would expect an error to be thrown is the version wasn't satisfied. 

### Actual behavior

Argument is ignored.

### Your environment

- IDE: Version 2023.05.0-daily+206 (2023.05.0-daily+206)
- OS: MacOS Ventura 13.4

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.176
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.7 (Conda)
      Path: /Users/emilhvitfeldt/miniforge3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources
      LibPaths:
        - /Users/emilhvitfeldt/Library/R/arm64/4.2/library
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK-
```

### PR DESCRIPTION
**Pull request by cderv**
This fixes #6071 

@cscheid I believe a877ae987fbd3d1dbf396491fa43355e39f42979 is what you intended to do in #2322 initially. Correct me if I am wrong. 

This will make 
````markdown
---
format:
  html:
    quarto-required: ">= 1000.4.375"
---

## Quarto
````

I don't think we add the necessary infrastructure to test for an Error in `quarto render `with a specific message. I have added a test and a way to test for this. 

@dragonstyle you may want to have a look - I did not found any way to leverage our `verify.ts` functions for this - there is a `printMessage()` verify function, but AFAIU when `quarto render` error, we do not produce any log, and also our `try() catch ()` will catch the `test.execute()` error, before we can apply a verify function. 

Anyway, this is an attempt :)

### CODE REVIEW

**Comment by cderv** [comment]
Just putting on hold after discussing with @dragonstyle. It will be better to fix our tests framework for `printsMessage` to work as expected.

**Comment by cderv** [comment]
Ok all good now. @dragonstyle this should be what we discussed. 

Let's see now if all the tests are passing after this change in `test.ts`

**Comment by cderv** [comment]
@cscheid @dragonstyle Ok to merge this ?

**Comment by cscheid** [comment]
The only problem here is that your change will break user documents that now rely on `quarto-version` rather than `quarto-required`...

**Comment by cderv** [comment]
Yes I know - I pinged you about that in https://github.com/quarto-dev/quarto-cli/issues/6071#issuecomment-1614311996

But really `quarto-version` for document is not documented at all AFAIK, and it was not intended in the first place from what I read on your original PR. So wouldn't it be a valid "breaking change" ?  
I am not sure this would be breaking much content as `quarto-version` for document is internal and not documented. 

If we don't want to do that, then we could support both for some time (deprecated with a warning). Or I am open to other solution - just currently this is not working as [documented](https://quarto.org/docs/reference/formats/html.html#format-options)

**Comment by cscheid** [comment]
Ok, I'm convinced. Let's merge this.

**Review by cscheid — APPROVED** [review]
LGTM.

**Pull request merged**
