### PR TITLE
Initial translation for Norwegian

### PR DESCRIPTION
**Pull request by ChristianWatkins**
## Description

Added Norwegian language translation

## Checklist

I have (if applicable):

- [ ] filed a [contributor agreement](../CONTRIBUTING.md).
- [ ] referenced the GitHub issue this PR closes
- [ ] updated the appropriate changelog

### CODE REVIEW

**Comment by cscheid** [comment]
Thank you! Can you file a CA by following the instructions on that link? We'll be happy to merge it after.

**Comment by ChristianWatkins** [comment]
Sure, but the link turns up as "Not Found".

**Comment by cscheid** [comment]
That's an annoying mistake on our side; the correct link should be https://github.com/quarto-dev/quarto-cli/blob/main/CONTRIBUTING.md

**Comment by ChristianWatkins** [comment]
No problem. So sign and send this?
https://rstudioblog.files.wordpress.com/2017/05/rstudio_individual_contributor_agreement.pdf

**Comment by cscheid** [comment]
Hi - did you get a chance to send this? I'd love to merge the PR.

**Comment by ChristianWatkins** [comment]
I did send and got the reply "thanks" from jj on Sun, 15 Jan.

**Pull request merged**
