### PR TITLE
mermaid,themes - update themes 

### PR DESCRIPTION
**Pull request by cscheid**
This PR makes mermaid flowcharts work well across all bootswatch themes, following our work-week discussions on Friday.

Specifically, it specializes the mermaid SCSS variables to each theme, and tweaks them as necessary.

It also changes one of the defaults across all themes in the CSS emitted by mermaid-init.js itself, so that the arrow end markers look nicer.

### CODE REVIEW

**Comment by cderv** [comment]
So cool ! Thanks for this. 

Initially I was thinking we could add each mermaid variables into an additional theme file per bootswatch theme. idea was to simplify the update of bootstrap and keep initial bootswatch without modification for quarto. 

But using git diff in an update is easy enough I guess. 

Just sharing what I would have done. All good - I'll note the idea for visual testing.

**Comment by cscheid** [comment]
> Initially I was thinking we could add each mermaid variables into an additional theme file per bootswatch theme. idea was to simplify the update of bootstrap and keep initial bootswatch without modification for quarto.

That might be the right way to do solve the problem. I already needed to add an additional theme file for the _default theme_, which doesn't have an .scss file by itself. But then, that caused all of these failures in CI for reasons I don't understand.

**Comment by cderv** [comment]
The error are related with all the missing them options. By adding the rules into the `_quarto_rules` layer, it means we are making it default for Quarto base layer 
https://github.com/quarto-dev/quarto-cli/blob/c73c11d82019072df4d6d0e3ecd436ca4298327b/src/format/html/format-html-shared.ts#L266-L290

So the variables associated with those rules, should also be defined in the defaults layer. See above what we do for each feature we have and need variables. 

I would really add some basic default in this base layer, which is used for HTML document  and not for reveal. This base layer will apply for HTML format without bootstrap 
https://github.com/quarto-dev/quarto-cli/blob/c73c11d82019072df4d6d0e3ecd436ca4298327b/src/format/html/format-html.ts#L417-L431


I really wonder if we should not try to make those mermaid SCSS information a specific quarto internal layer that we could add in every place  (no bootstrap, bootstrap, and revealjs

**Comment by cscheid** [comment]
I tried doing that, but then I couldn't make the non-default themes override the defaults. I think I tried adding them to different layers and couldn't make any of it work.

I know SCSS is hard, but honestly, I think we should consider rethinking this whole thing. It feels hopeless to do something robustly and extensibly.

**Comment by cderv** [comment]
> I know SCSS is hard, but honestly, I think we should consider rethinking this whole thing. It feels hopeless to do something robustly and extensible.

I was started to have the feeling to understand it ! 😅  But why not rethinking all this, at least for our internal code base so that it is easier to maintain. 

I find this layering system quite useful to split content, but the order matters, and currently the fact everything is split across our code base makes it hard to fully reason about. 

Do you want me to give it a try based on what I learnt by looking into this for revealjs theme ?

**Pull request closed without merging**
