### PR TITLE
typst: handle toc-title and toc-depth

### LINKED ISSUE #7822: Typst: Improve TOC support
### Bug description

Bring typst support up to the level of PDF as described in [PDF Basics](https://quarto.org/docs/output-formats/pdf-basics.html#table-of-contents).

In particular, add support for the `toc-depth`, and `toc-title` options.

### Steps to reproduce

````qmd
---
title: TOC
format: typst
number-sections: true
toc: true
toc-depth: 2
toc-title: "Outline"
---

## Section

### Subsection 

#### Subsubsection 

## Unlisted Section {.unnumbered .unlisted}
````

### Expected behavior

Like PDF output:
Screenshot 2023-12-07 at 12 54 06 PM

### Actual behavior

Screenshot 2023-12-07 at 12 54 34 PM

### Your environment

_No response_

### Quarto check output

_No response_

### PR DESCRIPTION
**Pull request by cscheid**
This closes #7822.

### CODE REVIEW

**Comment by cderv** [comment]
Some note on this change. 

This will now default to `toc-depth: 3` which is the Pandoc defaults, while Typst default to `none` (meaning all included) which was set explicitly in Pandoc's template. 

I think the default of 3 makes sense, and it like HTML or LaTeX. However, Typst allow for this special `none` value to include all. 

Should we have a way to set `toc-depth` to this value in Quarto ? Validation does not allow for now because Pandoc does not allow it (only `--toc-depth=[1-6]` is allowed. 

Just writing this here for reference in case this raises question in the feature, and I noticed this.

**Comment by cscheid** [comment]
Hm. I almost wonder if this is a Pandoc issue. For us to fix it entirely on our side, we would have to decide whether or not to forward `toc-depth` depending on the value. If it's `none`, we'd have to set it via some special metadata or something? That feels pretty ugly.

The behavior now is slightly different from the default Pandoc template, but I think it's better :)

**Comment by cderv** [comment]
> The behavior now is slightly different from the default Pandoc template, but I think it's better :)

Yes I agree. I opened FR in Pandoc for the support. If they do, maybe they will consider the none case. 
* https://github.com/jgm/pandoc/issues/9242

In the meantime, `toc-depth: 6` is the max value possible and will have the same effect. I believe 6 headers are the max anyway.

**Comment by cderv** [comment]
And Pandoc Dev has now support for `toc-depth`, but only numeric value directly passed to `output` `depth` field in Typst. 

So this will be available in next Pandoc. Should we add a comment note comment in our code ?

**Comment by cscheid** [comment]
We already have an item in our Pandoc update checklist to update defaults, etc, so we should not need a comment. But it wouldn't hurt!

**Pull request merged**
