### PR TITLE
Properly deal with remote URLs in preview images

### LINKED ISSUE #5005: Non-standard URLs display correctly inline but not on image grid
### Bug description

Note the weird non-standard URL below (contains commas and other punctuation)

```
---
title: Clabbered milk
date: '2017-02-02'
categories:
  - food
---

Here is a blog post, blah blah.

Note how the following images both display just fine from within this post.

![another image from the web](http://assets.bonappetit.com/photos/57bf31396a6acdf3485df7f9/5:4/w_1028,c_limit/koji-steak-1.jpg)

![](diet-assets/clabberedMilk.jpg)

But inside the grid view, the image preview is broken.

```
Find a working full example at this repo: [richardsprague/quartosample: extrapage](https://github.com/richardsprague/quartosample/tree/extrapage)

Using 1.3.294 on a Mac OS 13.2

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

### PR DESCRIPTION
**Pull request by dragonstyle**
Fixes #5005

### CODE REVIEW

**Comment by allenmanning** [comment]
@dragonstyle Is it reasonable to add a test to help catch potential future regressions?

**Comment by dragonstyle** [comment]
>  Is it reasonable to add a test

I originally tried and failed, but there is a selector that allows me to verify a specific src value for images, so upon trying a second time it was actually easy. added!

**Review by cscheid — APPROVED** [review]
LGTM. Is this another case where a broader review of the codebase could be a good idea?

**Comment by dragonstyle** [comment]
This is a result of me adding this capability at the end of feature development specifically dealing with preview images so not too likely to be causing downstream issues (I added a new way to inject these preview images, other usages are unchanged).

**Pull request merged**
