### PR TITLE
Test if quarto-latexmk can be built

### PR DESCRIPTION
**Pull request by yihui**
I've been trying to build quarto-latexmk nightly in the tinytex repo. It has been broken a couple of times before, so I'd like to add tests to make sure it can be successfully built here. It was broken about a week ago and I didn't notice it for some reason (likely due to afb256e42f95b791919a110d95fc1eb2c70990e3).

### CODE REVIEW

**Comment by yihui** [comment]
The tests failed as I expected. I get this error:

```
ERROR: TypeError: Cannot read properties of undefined (reading 'join')
```

and I don't know where it came from. @dragonstyle Any ideas?

**Comment by dragonstyle** [comment]
I'm not sure why this suddenly broke (it sort of looked broken the whole time honestly). I've made a change that should fix it here:

baae533aede3f90126a9bd290672b74e66e82123

I have a todo to add a test build of this to our repo as well as we keep not paying attention to this entry point...

**Comment by yihui** [comment]
The `join` error has been fixed indeed. The binaries are not generated, e.g., `package/dist/bin/quarto-latexmk/x86_64-unknown-linux-gnu` is an empty directory (I used `ls -R`): https://github.com/quarto-dev/quarto-cli/runs/4873920527?check_suite_focus=true

**Comment by dragonstyle** [comment]
Thank you for catching these - we an async issue that was allowing the process to exit before it was completing (wasn't awaiting the compile!). Fixed here https://github.com/quarto-dev/quarto-cli/commit/abe3d6dc209dd2ef3ff6e86148ba9ddbe51974cc . 

I also added a GH action in our repo to testing building the `quarto-latexmk` on linux and verifying that output is present. I will add other targets later, but this will hopefully catch errors like this further upstream of you!

**Comment by yihui** [comment]
Perfect! I can confirm that it's working now. I guess I can close this PR now. Thanks!

**Comment by dragonstyle** [comment]
Your PR is actually more complete and thorough than my test. If you're ok with it, I'd like to reopen it and use yours instead of the one I threw together (for some reason I was thinking this was an issue not a PR!).

**Comment by yihui** [comment]
Sure! I'll reopen and tweak it a little bit soon.

**Comment by yihui** [comment]
Okay, I think it's ready now. Please feel free to tweak it as you wish. Thanks!

**Comment by dragonstyle** [comment]
Thank you very much!

**Pull request merged**
