### PR TITLE
Lightbox - use description attr

### LINKED ISSUE #8607: Lightbox images descriptions don't work anymore with v1.4
### Bug description

Hi team :wave: 

With the lightbox extension, we used to be able to add descriptions to images

### Steps to reproduce

See [example](https://github.com/quarto-ext/lightbox/blob/a738ff253fd46dd0cdd6aa992178cb7561b70251/example.qmd#L27)

### Expected behavior

expected

### Actual behavior

actual

### Your environment

- Quarto version: 1.4.549
- OS: Ubuntu 20.04.6 LTS

### Quarto check output

```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      Chromium: 869685
      TinyTeX: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2019

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: /home/ycrouin/miniconda3/bin/python
      Jupyter: 5.7.1
      Kernels: [omitted for brevity ...]

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/opt/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/opt/quarto/share/jupyter/notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
There is an unactivated Python environment in venv. Did you forget to activate it?

[✓] Checking Jupyter engine render....OK
```

### PR DESCRIPTION
**Pull request by dragonstyle**
Use the description attribute if it is present. Fixes #8607

### CODE REVIEW

**Comment by th0ger** [comment]
Hi, the "description" (and "caption"?) attrs are not documented in https://quarto.org/docs/output-formats/html-lightbox-figures.html
Has it been added to the next release docs?

**Comment by cscheid** [comment]
> (and "caption"?)

`caption` is not a lightbox option.

> Has it been added to the next release docs?

We don't merge pre-release documentation ahead of a release, just to be clear.

> Hi, the "description" [attr is] not documented in https://quarto.org/docs/output-formats/html-lightbox-figures.html

Thanks - @dragonstyle I do think we are missing the schema key in src/resources/schema/document-lightbox.yml or am I confused here?

**Comment by phanindra-max** [comment]
Hi @dragonstyle and @cscheid

I am still facing the same issue as #8607, I cannot see the description of the images.

Here is my code:

```
---
title: Simple Lightbox Example
lightbox: auto
---


### Checking description for inline image

![Image with Lightbox treatment](https://media.istockphoto.com/id/1472089286/photo/magnifying-glass-on-a-stack-of-documents.jpg?s=1024x1024&w=is&k=20&c=hXHiYebtlgnKa8pBVCPmsbzbauaVOnEdqr1ZsebVaCY=){description="This description is not visible"}


### Checking in Code Chunk
```{r}
#| fig-cap: Simple demo R plot 
#| lightbox:
#|   description: This description is not visible
plot(1:10, rnorm(10))
```


This is the output: 

### Inline Image




### Code Chunk


I don't know what is going on here, but I also suspect this issue might be specifically happening on my device.


Thanks

**Comment by phanindra-max** [comment]
I just ran the `quarto check` and got this result

```
Quarto 1.4.550
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.550
      Path: C:\Users\phani\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: C:/Users/phani/AppData/Local/Programs/Python/Python312/python.exe
      Jupyter: 5.7.1
      Kernels: python3

(\) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\phani\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\phani\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
[>] Checking Jupyter engine render....OK
```
It says there is an issue with the Jupyter engine render but I don't know if that is what's causing the issue with the description.

I am kind of stuck at this stage and I am interested in contributing to this repo. Any input is much appreciated.

**Comment by th0ger** [comment]
Hi devs,
This PR fixes #8607, named "Lightbox images descriptions don't work anymore with **v1.4**".
Afaik the fix is only added in v1.5 (preview) branch.

So I'm a little confused about the semver/patching strategy for quarto. Will you not apply patches to stable releases (1.4.*), or are  we forced to step up in unstable preview branches (1.5.*) to receives patches?

Thanks a lot :-)

**Comment by cderv** [comment]
As you noticed @th0ger #8607 was a fix we made only in 1.5. To be clear, All the fixes we do for issues coming after the 1.4 stable release should not be considered as patches that will be applied also on 1.4. Only a few of those are selected to be patches and so will be backported to v1.4 branch and will be in the next patch release. 

This change was not marked as a change to be backported so it wasn't. @dragonstyle could this have been a backport candidate?

> Will you not apply patches to stable releases (1.4.), or are we forced to step up in unstable preview branches (1.5.) to receives patches?

So depending on the bug encountered, one could need to use the 1.5 pre-release or the next 1.4 patch release. Note that the "unstable preview branches (1.5)" is a bit strong - We don't have a 1.5 branch - dev version is on main, but no need to use this as we build pre-releases that pass all our tests. They are available in github release page as pre-release, and on our download page (https://quarto.org/docs/download/prerelease.html). They are less stable than 1.4 release for sure because they have new feature that could have some regression yet to be found. I don't say you should use those, just wanted to explain a little.

**Comment by th0ger** [comment]
@cderv Thanks for the clarification. I'm not sure I agree on the minor/patch version strategy, but I acknowledge that semver/API-pinning can be hard and oppinionated (especially for UI products), and backporting takes effort.

You mention that 1.5.* is "less stable than 1.4". But for Quarto that unfortunately doesn't necessarily mean that 1.4 is less buggy, since you don't apply all bugsfixes to the latest stable release. As a user who prioritize less features and less bugs, this makes the 1.4 vs. 1.5 pick unclear.
Anyway, it's okay to end the talk here if you like, as it's getting quite off-topic :-)

**Pull request merged**
