### PR TITLE
`quarto tools` help page improvment

### PR DESCRIPTION
**Pull request by cderv**
* `quarto tools list` is the way to list all status following change in d3a6418
* `quarto tools info` was not documented (I looked for it in one of the github discussion we had to find the syntax)

### CODE REVIEW

**Comment by jjallaire** [comment]
@dragonstyle didn't we deprecate "quarto tools" in favor verb based variants?

**Comment by dragonstyle** [comment]
We have deprecated that command (though it is still functional). In particular, I haven't replaced `quarto tools info <toolname>`, which prints a json summary of the tools (install status, paths, etc...). I wasn't sure what global command would make sense for this (e.g. `quarto info tool tinytex`, `quarto summarize tool tinytex`, 'quarto status tool tinytex`). 

I like `quarto info` I think but curious if you have a reaction / idea. The function for printing the tool is very straightforward so I can easily add the command and update the docs.

**Comment by dragonstyle** [comment]
FYI @cderv I'm going to close this since we have the tracking issues to deal with this post 1.0 - want to push as much as possible to post 1.0 wherever we can.

**Comment by cderv** [comment]
Thanks ! This all makes sense.

**Pull request closed without merging**
