### PR TITLE
tables - allow disabling striping etc in computational tables

### LINKED ISSUE #6945: Option to disable table striping in computational tables?
### Bug description

In this issue, https://github.com/quarto-dev/quarto-cli/issues/922#issuecomment-1640093837, there's a difference in how tables are rendered by default: non-computational tables made with Markdown don't have the `.striped` class included, while tables generated with chunks (like with `knitr::kable()` or with `gt::gt()` do.

The rational for including stripes and condensed spacing by default makes sense, since tables full of numbers often need to be more information-dense. Sometimes, though, {kable} and {gt} can be used to create less number-heavy tables and just present text. As of Quarto 1.4.376, the `.striped` class seems hard-baked-in and can't be removed, though (though I might be missing some option to disable it)

### Steps to reproduce

This example uses {gt} to generate a text-based table. Row striping appears (`<table class="gt_table table table-sm table-striped small" ...>`) regardless of the `row_striping` option in `gt::opt_row_striping()` (which is a gt thing, not a quarto thing, but quarto's table rendering is inserting its own table class here)

````qmd
---
title: "Testing"
---

```{r}
dplyr::tibble(Animal = c("Bat", "Cat", "Dog"), `Has wings` = c("Yes", "No", "No")) |> 
  gt::gt() |> 
  gt::opt_row_striping(row_striping = FALSE)
```
````

image

### Expected behavior

It would be nice to have a table without stripes. [In the documentation](https://quarto.org/docs/prerelease/1.3/tables.html#bootstrap-classes-can-be-added-to-tables) it shows that it's possible to add a bunch of different bootstrap classes to non-computational tables:

```
| fruit  | price  |
|--------|--------|
| apple  | 2.05   |
| pear   | 1.37   |
| orange | 3.09   |

: Fruit prices {.striped .hover}
```

### Actual behavior

However, that `.striped` class is hard-coded for computational output and there's no way I can find to disable it, so all kable and gt tables have stripes regardless of controlling stripes with kable- and gt-specific settings.

### Your environment

- Quarto: 1.4.376
- IDE: 2023.06.2+561
- R: 4.3.1
- OS: macOS Ventura 13.5.2

### Quarto check output

```bash
Quarto 1.4.376
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.376
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2022.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/andrew/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.3
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: python3

(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
(|) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by cscheid**
Closes #6945.

### CODE REVIEW

**Comment by rressler** [comment]
I found the discussion in https://github.com/quarto-dev/quarto-cli/issues/6945. quite helpful as I tried to create different formatting for R code chunks from SQL chunks 

Did you know if the disabling of quarto table processing with tables was tested on output from an SQL chunk?

I tried all three options in https://quarto.org/docs/authoring/tables.html#disabling-quarto-table-processing in the file below (since removed) and the rendered output from an SQL code chunk was still the default .table-striped.

I created new class definitions for .table-striped in the document and was able to get what I needed. 

I am not aware of a sample database I could use but the flights one below is just from writing data frames from nycflights13 to a duckdb database.

Thanks,

---
format: html
embed-resources: true
knitr:
  opts_chunk: 
    echo: fenced
    class.source: rsource
    class.output: routput
---

```{css, echo = FALSE}
pre.sqlsrc {
  background-color: lightblue;
}

.table-striped {
  --bs-table-striped-bg:white;
  border: 8px solid lightblue;
  font-size: .75em;
  line-height: 1.em;
}

.table-striped  tr:nth-child(even) {
  background-color: white;
  outline-color top: 6px solid lightblue;
  color: darkblue;
}

.table-striped  tr:nth-child(odd) {
  background-color: white;
}

.table-striped th {
  background-color: white;
  border-color: 5px solid lightblue;
  color: darkblue;
}
.table-striped  tr:last-child {
      border-bottom: 2px solid lightblue;
}
 
pre.rsource {
  background-color: lightgreen;
  filter: brightness(90%); /* Makes it slightly lighter */
  #opacity: 1.0; /* 50% transparent */
}
pre.routput {
  border: 6px solid lightgreen;
}
```

```{r, include=FALSE}
knitr::opts_hooks$set(
  class.source = function(options) {
    if (options$engine == "sql") {
      options$class.source <- 'sqlsrc'
     # options$class.output <- 'table-striped'
    }
    return(options)
  }
)
```


```{r}
#| label: createData
#| message: false
library(DBI)
library(duckdb)
```

```{r}
con <- dbConnect(duckdb(dbdir = "./data/flights.duckdb", read_only = TRUE))
class(con)
```

**Comment by cscheid** [comment]
> I tried all three options in https://quarto.org/docs/authoring/tables.html#disabling-quarto-table-processing in the file below (since removed) and the rendered output from an SQL code chunk was still the default .table-striped.

You've linked to a different table processing feature (I know, it is confusing). The feature you linked to is our ability to take HTML tables and convert them to Pandoc's internal format so that we can produce output in non-HTML formats.

The ability to remove styling is done by adding `classes: plain` to your `r` code cell. That works independently of whether the tables are authored in HTML or not. Something like:

````
```{r}
#| classes: plain
tibble::tribble(
  ~fruit,   ~price,
  "apple",  2.05,
  "pear",   1.37,
  "orange", 3.09
) |> 
  gt::gt()
```
````

**Comment by rressler** [comment]
Thanks for the clarification. Adding classes: plain changes the div class to div class plain but the tables inside are 
still table-striped in both SQL and R output (see the screenshot). Am i missing something? 

Thanks

Screenshot 2024-05-16 at 8 23 44 AM

PDF of HTML in browser
[untitled3.pdf](https://github.com/quarto-dev/quarto-cli/files/15334942/untitled3.pdf)

[flights.db](https://github.com/AU-datascience/data/blob/main/413-613/flights.duckdb)

---
format: html
embed-resources: false
knitr:
  opts_chunk:
    echo: fenced
---

```{r}
#| label: createData
#| message: false
library(DBI)
library(duckdb)
```

```{r}
con <- dbConnect(duckdb(dbdir = "./data/flights.duckdb", read_only = TRUE))
class(con)
```

```{sql}
#| label: sql-test
#| connection: con
DESCRIBE airlines;
```

```{sql}
#| label: sql-test2
#| connection: con
#| classes: plain
DESCRIBE airlines;
```

```{r}
my_df <- tibble::tribble(
  ~fruit,   ~price,
  "apple",  2.05,
  "pear",   1.37,
  "orange", 3.09
) 
my_df|> 
  gt::gt()
```

```{r}
#| classes: plain
my_df|> 
  gt::gt()
```

```{r}
#| class.output: plain
my_df|> 
  gt::gt()
```

```{r}
#| label: disconnect
dbDisconnect(con, shutdown = TRUE)
```

**Comment by cderv** [comment]
@rressler can you help us and format your issue correctly ?  You can edit above post following
https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us

You are missing some more backticks on external markdown part so that document shows ok. See the doc. 

Thank you !

**Comment by cscheid** [comment]
You probably need a very recent version of Quarto. Note that you're commenting on a pull request that was merged last week.

**Comment by rressler** [comment]
I updated to the pre-release with the change ([v1.5.37](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.5.37)) and it works now. Output of plain is table.table for SQL code output and gt.table for GT-generated tables.
Thanks!

**Pull request merged**
