### PR TITLE
Increase a11y-light token contrast

### PR DESCRIPTION
**Pull request by batpigandme**
* Fixes accessibility failure for token color so that it works with Quarto's default code-block background color.

### CODE REVIEW

**Review by cscheid — COMMENTED** [review]
lgtm.

I do think we're targeting the v1.2 branch right now (`main` will become v1.1 and it's in freeze). @jjallaire do you want to sneak this one into v1.1?

**Comment by jjallaire** [comment]
No we are frozen on v1.1 pre-release. Let's target this for v1.2.

**Comment by cscheid** [comment]
@batpigandme All this needs to merge is an addition to `news/changelog-1.2.md`. I can do that on a separate pull request if you want, or if you want this PR to go through, please go ahead and do that. Thanks!!

**Comment by jjallaire** [comment]
Let's see if we can figure out how this can be less than 97 commits :-)

Maybe just start over with a new branch applying just the change in token contrast?

**Comment by batpigandme** [comment]
@jjallaire, yep! Just was thinking the same thing. I'll just re-do the PR—it's changes to two files!

**Comment by jjallaire** [comment]
Great, thanks!

**Comment by batpigandme** [comment]
Now in #2267

**Pull request closed without merging**
