### PR TITLE
rename create-project --type site to --type website

### LINKED ISSUE #92: --type: alias "website" as an alias for "site"
The documentation talks about "website", yet the CLI only supports "site". Should the CLI support "website" as equivalent to "site"?

```
quarto create-project --type website
ERROR: Error: Project type must be one of default, site, book, but got "website".
    at Object.value (file:///Users/aron/dev/rstudio/quarto-cli/src/command/create-project/cmd.ts:35:17)
    at parseFlags (https://deno.land/x/cliffy@v0.19.3/flags/flags.ts:168:34)
    at Command.parseFlags (https://deno.land/x/cliffy@v0.19.3/command/command.ts:1113:22)
    at Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:896:58)
    at Command.parse (https://deno.land/x/cliffy@v0.19.3/command/command.ts:870:33)
    at quarto (file:///Users/aron/dev/rstudio/quarto-cli/src/quarto.ts:59:64)
    at file:///Users/aron/dev/rstudio/quarto-cli/src/quarto.ts:76:11
```

### PR DESCRIPTION
**Pull request by thomasballinger**
Resolves #92 deprecating 'site' in favor of website, but both still work.

Changed error message:

    $ quarto create-project mysite4 --type asdf
    ERROR: Error: Project type must be one of default, website, book or site (deprecated) but got "asdf".
        ...

Is this the level of deprecation you were thinking of @jjallaire?

There are a couple instances of the string "site" that I didn't change but wasn't sure about.

I haven't run any automated tests so I'll look for CI results.

### CODE REVIEW

**Comment by thomasballinger** [comment]
Since communicating these to me may be more work than making the changes, feel free to take this over or make another PR. Thanks for the very quick feedback on PRs so far!

**Comment by thomasballinger** [comment]
I see a lot of uses of `site` in this file that I'm not sure if you want to change https://github.com/quarto-dev/quarto-cli/blob/main/src/project/types/website/website-config.ts#L26
I'll leave the PR alone for now in case you do want to go for it.

**Comment by jjallaire** [comment]
Okay, I'll close this PR (thanks again for getting this rollign!). Work continues on this branch: https://github.com/quarto-dev/quarto-cli/tree/feature/project-site-to-website

**Comment by jjallaire** [comment]
Draft PR is here: https://github.com/quarto-dev/quarto-cli/pull/160

**Pull request closed without merging**
