### PR TITLE
Creates _language-pt.yml

### PR DESCRIPTION
**Pull request by beatrizmilz**
Hello! 
In this PR, there is a new file called `src/resources/language/_language-pt.yml` that contains translated terms to Portuguese. 

Related to this issue: https://github.com/quarto-dev/quarto-web/issues/38

Thank you

### CODE REVIEW

**Comment by jjallaire** [comment]
The updated translations are available in v0.2.273: https://github.com/quarto-dev/quarto-cli/releases/tag/v0.2.273

**Comment by beatrizmilz** [comment]
Thanks JJ! I installed it, and added 'lang: pt' on the '_quarto.yml' and it worked! https://github.com/beatrizmilz/2021-senacamb-intro-R/blob/1e4a97111030788213d1029599442edabd4743e7/_quarto.yml#L4

Live example: https://beatrizmilz.github.io/2021-senacamb-intro-R/materiais.html (if you use the search tool is easy to see that it is in Portuguese :tada: )


Thanks again, JJ!

**Comment by jjallaire** [comment]
@beatrizmilz Does this look like the correct translation of "Appendices" to Portuguese? https://github.com/quarto-dev/quarto-cli/commit/42cf9d5e4d9d04f2a8725d5e47595ca39439c72b#diff-6fb0adf5e45e61b038661640bde303e0aa09416eeb516f0918195e3d4a788861

**Comment by beatrizmilz** [comment]
Hi JJ! 
Yes, the translation of "Appendices" to Portuguese is "Apêndices" :) It is correct.

**Pull request merged**
