### PR TITLE
add title canonicalization html postprocessor

### LINKED ISSUE #10567: breadcrumbs only appear if title set in topmatter
### Bug description

The docs on [breadcrumbs](https://quarto.org/docs/websites/website-navigation.html#breadcrumbs) mention they will be displayed by default. It appears that when `title:` is not set in the top-matter, then they are not displayed.

Note that in this issue I'll refer to three possible meanings of title:

1. `_quarto.yml` sidebar `text:` title
2. qmd topmatter title
3. qmd header title

Currently, quarto requires (2) to be set. When this happens, (1) gets shown if set. Otherwise, (2) gets shown.

### Steps to reproduce

**_quarto.qmd**

```
project:
  type: website

website:
  sidebar:
    - contents:
      - section: "Tutorials"
        contents:
          - text: Tutorial sidebar title
            href: tutorials.qmd
```

**tutorial.qmd**

``````
---
# uncomment below to see breadcrumbs say "Tutorial sidebar title"
# title: Tutorial topmatter title
---

# Tutorial qmd first header

abc
``````

### Expected behavior

breacrumb for tutorial page should say "Tutorial sidebar title".

### Actual behavior

No breadcrumb shown

### Your environment

mac osx

### Quarto check output

```bash
Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.5
      Path: /Users/machow/.pyenv/versions/3.9.5/bin/python3
      Jupyter: 5.3.1
      Kernels: <removed>

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library
      knitr: 1.39
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by cscheid**
Closes #10567.

This fixes the immediate bug, but the HTML emitted is still not exactly the same; we have a stray `section` tag on the document with an explicit `# title` heading (or, we have a missing `section` tag on the document with a `title: title` declaration).

### CODE REVIEW

**Comment by cderv** [comment]
> The title element disappeared from the document meta block in the HTML output. Not sure if this was intended. subtitle etc are still there, if specified. We had been using this to fetch the title.

This seems like an issue. HTML template as the field and it should be field with pagetitle which by default is supposed to be the same as title
https://github.com/quarto-dev/quarto-cli/blob/39baf4081f184fe090974295b48d1beab32cd1e4/src/resources/formats/html/pandoc/metadata.html#L23
I'll look into that, based on the pkgdown bug report. 

I am surprised that this change that seems to be targeted document without a `title` element. And the quarto vignette has this element. 🤔

**Comment by jayhesselberth** [comment]
@cderv We had been fetching the title from the meta block:

here: 

https://github.com/r-lib/pkgdown/blob/dfa28bef27858bd442334b5cce8f645d555914be/R/build-quarto-articles.R#L126

then here:

https://github.com/r-lib/pkgdown/blob/dfa28bef27858bd442334b5cce8f645d555914be/R/build-quarto-articles.R#L142-L147

**Comment by cderv** [comment]
Ok I did not understood this `meta` block because this is something that comes from the **pkgdown** side. The quarto rendering is done with a custom template that create this block
https://github.com/r-lib/pkgdown/blob/dfa28bef27858bd442334b5cce8f645d555914be/inst/quarto/template.html#L25-L48

````
<div class="meta">
$if(title)$
  <h1>$title$</h1>
$endif$

$if(subtitle)$
  <p class="subtitle">$subtitle$</p>
$endif$

$for(author)$
  <p class="author">$author$</p>
$endfor$

$if(date)$
  <p class="date">$date$</p>
$endif$

$if(abstract)$
  <div class="abstract">
  $abstract$
  </div>
$endif$

</div>
````

In the output by the specific call to `quarto render` made by **pkgdown** (with some non-default meta), it ends up empty. This block should be filled with the $title$` pandoc variable, and it is not. This is the main issue. I'll try to make a minimal reprex and open a new issue.

**Comment by cderv** [comment]
Ok so now I understand. 

Within pkgdown, the custom template is applying which leads to this in the HTML **before** Quarto postprocessing
````html
<div class="meta">
  <h1>My cool title</h1>
</div>
````

However, as the custom template does not use `title-block.html` partial, it will trigger the post processing from this PR. 
https://github.com/quarto-dev/quarto-cli/blob/39baf4081f184fe090974295b48d1beab32cd1e4/src/format/html/format-html-title.ts#L205

and a title block will be created anyway by this new post-processing. The `h1` from the custom template is caught
https://github.com/quarto-dev/quarto-cli/blob/39baf4081f184fe090974295b48d1beab32cd1e4/src/format/html/format-html-title.ts#L210
and the `h1` that **pkgdown** expect will be moved 
https://github.com/quarto-dev/quarto-cli/blob/39baf4081f184fe090974295b48d1beab32cd1e4/src/format/html/format-html-title.ts#L238

So this PR has indeed bad side effect on custom **pkgdown** and custom template. I'll open a separate issue with those informations.

**Comment by jayhesselberth** [comment]
@cderv your comment above suggests that we can just use the `title-block.html` partial. Is that one way around this issue?

**Comment by cderv** [comment]
Are you looking for workaround until we fix this or a lasting solution for pkgdown side ?

**Comment by jayhesselberth** [comment]
CRAN wants an updated pkgdown [by Dec 24](https://cran.r-project.org/web/packages/pkgdown/index.html) to address this issue so a workaround would be fine for now.

**Comment by cscheid** [comment]
@cderv @jayhesselberth Thanks for tracking this down. Let's make sure we fix this very soon if possible (eg, the next couple of days). Let's also add a regression test that explicitly exercises the pkgdown vignette path.

@jayhesselberth We aren't planning on major changes, but are likely to change the HTML structure over time. Nevertheless, the expectation is that we'll always document when we do. This specific issue interacts with the custom templates code paths in a subtle way, which is why it didn't come up during testing.

**Pull request merged**
