### PR TITLE
resolve link tags correctly in html dependencies

### PR DESCRIPTION
**Pull request by cscheid**
This addresses #4304.

### CODE REVIEW

**Comment by jdlom** [comment]
Should'nt there also a function named `resolveLinkDependencies` ?

**Review by dragonstyle — APPROVED** [review]
doh! looks good.

**Comment by dragonstyle** [comment]
I'm not sure- what would you expect `resolveLinkDependencies` to do?

**Comment by cscheid** [comment]
(I'm going to merge this, but you can continue the `resolveLinkDependencies` here, and then open a new issue if necessary!)

**Pull request merged**
