### PR TITLE
Import patch from conda-forge to a new quarto-bld command

### LINKED ISSUE #6575: Add a `prepare-external` command to `quarto-bld`
This follows discussion at 

* https://github.com/conda-forge/quarto-feedstock/issues/27

Idea is to move the patch there (https://github.com/MattF-NSIDC/quarto-feedstock/blob/95a3bd9494f63a8d1eafd18395be9437e31943d3/recipe/0001-add-external-installer-command-for-packagers-like-co.patch) as a command in `quarto-bld`

cc @mfisher87

### PR DESCRIPTION
**Pull request by cderv**
From this commit version: https://github.com/conda-forge/quarto-feedstock/blob/56a863345810f5a53a19c5016dfc3fe953072f4d/recipe/patches/0001-add-external-installer-command-for-packagers-like-co.patch

This closes #6575 for https://github.com/conda-forge/quarto-feedstock/issues/27

@mfisher87 would you be able to try the PR ? 

@dragonstyle I put you as review on this for your insight. Also should we test it in our test suite ?

### CODE REVIEW

**Comment by dragonstyle** [comment]
This looks pretty good to me. I don't think we have a lot of tests for the `quarto-bld` command (or perhaps even any?) - since it has historically been relatively inward facing we haven't really needed it. 

This is a place where third parties might depend upon it, though I'm not sure what we'd use to verify that the command worked in a test (other than perhaps the presence of some files or perhaps checking a few specific sentinel files). If we get too smart in the verification I think it will be a maintenance nuisance, so I'd probably favor putting a test here without a good verification story.

**Comment by cderv** [comment]
Really no hurry ! Thank you for taking the time to help with this conda-forge package !

**Comment by mfisher87** [comment]
Started testing. I was not able to build from this branch because Quarto 1.4.x requires a pandoc version that's not on conda-forge yet. 

I rebased this change on to 1.3.450 and got significantly further; encountered an error at "Building JS assets" in the `prepare-dist` step. I re-tested without this change and looks like this error occurs on the feedstock main branch as well; so something changed and it wasn't the feedstock code or the Quarto code. My first guess was that a new, incompatible version of something was released since the last build, but `acorn` is a vendored dependency. Any ideas?

```
Building JS assets                                                                                                                                                                             
/home/robatt/.local/share/miniconda3/conda-bld/quarto_1694355633721/work/src/resources/types/schema-types.ts                                                                                   
Checked 1 file                                                                                                                                                                                 
ERROR: SyntaxError: Unexpected token (21283:9)                                                                                                                                                 
                                                                                                                                                                                               
SyntaxError: Unexpected token (21283:9)                                                                                                                                                        
    at Parser2.pp$4.raise (file:///home/robatt/.local/share/miniconda3/conda-bld/quarto_1694355633721/work/src/vendor/cdn.skypack.dev/-/acorn@v7.4.1-aIeX4aKa0RO2JeS9dtPa/dist=es2019,mode=impo
rts/optimized/acorn.js:2527:13)                                                                                                                                                                
    at Parser2.pp.unexpected (file:///home/robatt/.local/share/miniconda3/conda-bld/quarto_1694355633721/work/src/vendor/cdn.skypack.dev/-/acorn@v7.4.1-aIeX4aKa0RO2JeS9dtPa/dist=es2019,mode=i
mports/optimized/acorn.js:471:8)                                                                                                                                                               
    at Parser2.pp.expect (file:///home/robatt/.local/share/miniconda3/conda-bld/quarto_1694355633721/work/src/vendor/cdn.skypack.dev/-/acorn@v7.4.1-aIeX4aKa0RO2JeS9dtPa/dist=es2019,mode=impor
ts/optimized/acorn.js:468:26)                                                                                                                                                                  
    at Parser2.pp$3.parseMethod (file:///home/robatt/.local/share/miniconda3/conda-bld/quarto_1694355633721/work/src/vendor/cdn.skypack.dev/-/acorn@v7.4.1-aIeX4aKa0RO2JeS9dtPa/dist=es2019,mod
e=imports/optimized/acorn.js:2354:8)                                                                                                                                                           
    at Parser2.pp$1.parseClassMethod (file:///home/robatt/.local/share/miniconda3/conda-bld/quarto_1694355633721/work/src/vendor/cdn.skypack.dev/-/acorn@v7.4.1-aIeX4aKa0RO2JeS9dtPa/dist=es201
9,mode=imports/optimized/acorn.js:1143:23)                                                                                                                                                     
    at Parser2.pp$1.parseClassElement (file:///home/robatt/.local/share/miniconda3/conda-bld/quarto_1694355633721/work/src/vendor/cdn.skypack.dev/-/acorn@v7.4.1-aIeX4aKa0RO2JeS9dtPa/dist=es20
19,mode=imports/optimized/acorn.js:1130:8)                                                                                                                                                     
    at Parser2.pp$1.parseClass (file:///home/robatt/.local/share/miniconda3/conda-bld/quarto_1694355633721/work/src/vendor/cdn.skypack.dev/-/acorn@v7.4.1-aIeX4aKa0RO2JeS9dtPa/dist=es2019,mode
=imports/optimized/acorn.js:1055:24)                                                                                                                                                           
    at Parser2.pp$3.parseExprAtom (file:///home/robatt/.local/share/miniconda3/conda-bld/quarto_1694355633721/work/src/vendor/cdn.skypack.dev/-/acorn@v7.4.1-aIeX4aKa0RO2JeS9dtPa/dist=es2019,m
ode=imports/optimized/acorn.js:1970:19)                                                                                                                                                        
    at Parser2.pp$3.parseExprSubscripts (file:///home/robatt/.local/share/miniconda3/conda-bld/quarto_1694355633721/work/src/vendor/cdn.skypack.dev/-/acorn@v7.4.1-aIeX4aKa0RO2JeS9dtPa/dist=es
2019,mode=imports/optimized/acorn.js:1797:19)                                                                                                                                                  
    at Parser2.pp$3.parseMaybeUnary (file:///home/robatt/.local/share/miniconda3/conda-bld/quarto_1694355633721/work/src/vendor/cdn.skypack.dev/-/acorn@v7.4.1-aIeX4aKa0RO2JeS9dtPa/dist=es2019
,mode=imports/optimized/acorn.js:1775:17)                                                                                                                                                      
```

**Comment by cderv** [comment]
Thanks ! 

> Started testing. I wasn't able to build from this branch because Quarto 1.4.x requires a pandoc version that isn't on conda-forge yet.

Yes we updated Pandoc - https://pandoc.org/releases.html. Do we know if conda-forge pandoc is release quickly after a new Pandoc release ? 

>  I re-tested without this change and looks like this error occurs on the feedstock main branch as well

Regarding `acorn` issue; @dragonstyle any idea ? I don't know well this mecanism. 

@mfisher87 can you see some difference any JS dependencies from previous working build and the new build ? 
If this is something related to external node dependencies we should have the issue also while build 1.3.450 locally ?

**Comment by mfisher87** [comment]
> can you see some difference any JS dependencies from previous working build and the new build ?

Unfortunately, the 1.3.450  build logs are no longer available, so I don't have access anymore to the resolved JS dependencies from a past working build log: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=757337 . How to access the dependency manifest from a built PyPI or conda artifact? I found evidence that `acorn` is at `7.4.1` in Quarto `1.3.450` by `grep`, but I think that's a fairly naive approach :)

```
var version1 = "7.4.1";
Parser.acorn = {
    Parser,
    version: version1,
    ...
};
```

>If this is something related to external node dependencies we should have the issue also while build 1.3.450 locally ?

Doing the build for 1.3.450 locally fails with this error, which is why I think potentially an external dependency issue is at play. If you wouldn't mind, could you give it a try? Perhaps there's actually an issue with my build machine. To do so, clone the feedstock and run `build-locally.py` from the main branch (that's where the last successful build occurred). I expect you should see the same error, but I'll be very glad to be wrong on that one :)

**Comment by cderv** [comment]
This was solved by @dragonstyle already in https://github.com/quarto-dev/quarto-cli/commit/0fea9ec2462db44e3e343b8eabe86950b90117fe without having this PR merged. 

So this is outdated. 

@mfisher87 whatch out because the name of the command has changed from your patch. 

https://github.com/quarto-dev/quarto-cli/blob/770c47fbfeefe404fa43799116922bdb7c47a3c1/package/src/bld.ts#L112-L116

I'll close this. We can open new issue if there are problems to build the feedstock

**Pull request closed without merging**
