### PR TITLE
WIP: typst fig align code cell

### LINKED ISSUE #8797: Centered tables from code using typst
From a simpler example:

Note that you can use `keep-typ` to investigate the Typst code.

Let's take a simpler/smaller example.

````qmd
---
format: typst
keep-typ: true
engine: knitr
---

| Name | Age |
|------|-----|
| John | 23  |


```{r}
knitr::kable(data.frame(name = "John", age = 23))
```
`````

This will produce the following code for both tables:

<table>
<tr><th>Markdown table</th><th>Generated table</th></tr>
<tr><td>

````typst
#figure(
align(center)[#table(
  columns: 2,
  align: (col, row) => (auto,auto,).at(col),
  inset: 6pt,
  [Name], [Age],
  [John],
  [23],
)]
)
````

</td><td>

````typst
#block[
```r
knitr::kable(data.frame(name = "John", age = 23))
```

#block[ #<- This is the issue causing the table to be not centered
#figure(
align(center)[#table(
  columns: 2,
  align: (col, row) => (left,right,).at(col),
  inset: 6pt,
  [name], [age],
  [John],
  [23],
)]
)

]
]
````

</td></tr>
</table>

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8768

<div type='discussions-op-text'>

<sup>Originally posted by **psads-git** February 17, 2024</sup>
Consider the following `quarto` document. If `format` is `pdf`, the output is a centered table. However, when `format` is `typst`, the resulting table is left-aligned. Is it possible to get the table centered with `format: typst` likewise as with `format: pdf`? Thanks!

````
---
format: typst
papersize: a4
fontsize: 12pt
margin:
  x: 2.54cm
  y: 2.54cm
jupyter: python3
---

```{python}
import seaborn as sns

iris = sns.load_dataset('iris')
iris.head()
```
````</div>

### PR DESCRIPTION
**Pull request by gordonwoodhull**
@cscheid, here is a proposed solution for Typst `fig-align` (#8767) for discussion at our meeting today.

It simply marks `.cell > .cell-output-display` as `.quarto-scaffold`, maybe too broad:
- There's a good chance this will "accidentally" fix #8797, will test now
- What happens if there are multiple plot outputs? Existing code skips that case but I think expectation is that `fig-align` should be applied to all. (I'll check that as well.)

Note we can't directly test if alignment is working, we can only test if extra blocks surround the `#align()`.

Another possible fix can be made in post-processing, messier but more focused. See alternate branch here:
https://github.com/quarto-dev/quarto-cli/compare/fix/typst-fig-align-code-cell-in-post?expand=1

### CODE REVIEW

**Comment by gordonwoodhull** [comment]
Interesting.. I'll see if `\s*` works instead of `\n`

**Comment by gordonwoodhull** [comment]
Thanks @cderv, that’s the universal newline and most precise.

**Comment by gordonwoodhull** [comment]
Superceded by #9052

**Comment by cderv** [comment]
Thanks for closing. Can we delete the branch `fix/typst-fig-align-code-cell` in the repo then ? 

just asking for keep branch numbers in remotes cleaned

**Comment by gordonwoodhull** [comment]
Thanks @cderv, deleted this and a bunch of other temporary branches I had.

**Pull request closed without merging**
