### PR TITLE
listing - link activation for categories should work on any window.lo…

### LINKED ISSUE #10710: blog output: tag links don't work from pages called with an anchor URL
### Bug description

If I open this URL this URL that contains an anchor

https://quarto.org/docs/blog/posts/2024-07-02-beautiful-tables-in-typst/#cars-heatmap-gt-r

the links of the page tags does not work, the links are not active

image

### Steps to reproduce

- open https://quarto.org/docs/blog/posts/2024-07-02-beautiful-tables-in-typst/#cars-heatmap-gt-r and try to click on a tag

### Expected behavior

To have the tag links work

### Actual behavior

The tag links not work

### Your environment

The env used for quarto website

### Quarto check output

The output of quarto website

### PR DESCRIPTION
**Pull request by cderv**
closes #10710

`quarto.js` processing for activating link should be impacted by a query or hash part in the `window.location`

This simple fix ensure quarto does the categories search by comparing a clean offset path. 

This has been tested and verified against a simple website with blog post. And also in browser console for quarto-web. 

Test can't really be added because this is in-browser processing.

### CODE REVIEW

**Comment by cscheid** [comment]
> Test can't really be added because this is in-browser processing.

Is there no way for us to do something with Playwright? (I think we don't need to in this case, but I'm trying to understand the claim you made)

**Comment by cscheid** [comment]
(Looks good to me!)

**Comment by cderv** [comment]
> Is there no way for us to do something with Playwright? (

Oh sure with playwright. I was thinking no way in our current smoke and smoke-all way. 
But now I see better and indeed with playwright it will be possible.

**Comment by cderv** [comment]
Test with playwright added.

**Comment by aborruso** [comment]
Thank you very much

**Pull request merged**
