### PR TITLE
IDE tooling - make code cell detection consistent across editor modes

### LINKED ISSUE #8652: Quarto autocompletion fails for chunks with options in chunk header
### Bug description

From here:

https://github.com/quarto-dev/quarto-cli/blob/7b1e6d1cda0ae363de3ae602e3839562765b0dee/src/resources/editor/tools/yaml/web-worker.js#L33143-L33146

It appears that the YAML web worker that handles completions doesn't allow headers like:

`````
```{r label}
#| echo: 
```
`````

That is, the inline "label" chunk option causes rejection of the completion request.

### Steps to reproduce

Create an R Markdown document in RStudio, open it in the visual editor, and try to include Quarto-style YAML chunk options. For example:

`````
```{r label}
#| echo: 
```
`````

Then, request completions.

### Expected behavior

Quarto's bundled YAML web-worker should be able to provide completions.

### Actual behavior

Nothing is provided.

### Your environment

RStudio 2024.04.1 (dev build); macOS 14.2.1.

### Quarto check output

```
> system("quarto check")
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin
```

### PR DESCRIPTION
**Pull request by cscheid**
Closes #8652.

### CODE REVIEW

**Comment by cscheid** [comment]
@kevinushey, can you please test this branch and verify that the fix is good? We have a mechanism for adding these to our test suite but it's not very good.

**Comment by kevinushey** [comment]
Thanks -- looks good!

Screenshot 2024-02-08 at 5 34 47 PM

Just to confirm; I built Quarto using the repository `./configure.sh` script, and then set `RSTUDIO_QUARTO = ~/.local/bin/quarto` to use that copy of Quarto.

```
kevin@MBP-P2MQ:~/projects/quarto-cli [bugfix/8652]
$ quarto check
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/kevin/projects/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/kevin/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: 5.3.0
      Kernels: ir, ark

      NOTE: No Jupyter kernel for Python found

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/kevin/Library/R/arm64/4.3/library
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by kevinushey** [comment]
Sorry -- I'm now realizing this PR breaks things for regular Quarto chunks 😞 

This bit:

https://github.com/quarto-dev/quarto-cli/pull/8657/files#diff-c6a6e88b928985a9eab8677faaf706609d423172095052442d95363aae0dac2fR982

should probably be using `.*` rather than `.+` to eat up the rest of the stuff in the block.

**Comment by cscheid** [comment]
Oops. Ok.

**Comment by cscheid** [comment]
On `main` now; can you check?

**Comment by kevinushey** [comment]
Can confirm all is good now!

**Pull request merged**
