### PR TITLE
Update table term for french in _language.yml.

### PR DESCRIPTION
**Pull request by famuvie**
Use Tableau instead of Table.

Is there a standard reference for these terms? Working in France, I find that my French colleagues use the term "Tableau" instead of "Table" in reports.

## Description

Change the term "Table" by "Tableau" in the French language specification, according to common use.

## Checklist

I have (if applicable):

- [ ] filed a [contributor agreement](https://github.com/quarto-dev/quarto-cli/blob/main/CONTRIBUTING.md).
- [ ] referenced the GitHub issue this PR closes
- [ ] updated the appropriate changelog

### CODE REVIEW

**Comment by cderv** [comment]
> Change the term "Table" by "Tableau" in the French language specification, according to common use.

I think this is your proposal. but this PR is invalid because you are modifying the default file, and not the french version of this. 

We do use `Table`

https://github.com/quarto-dev/quarto-cli/blob/01b2f041fb633b2b9bd597dc938e0b9d1b271c0b/src/resources/language/_language-fr.yml#L83

https://github.com/quarto-dev/quarto-cli/blob/01b2f041fb633b2b9bd597dc938e0b9d1b271c0b/src/resources/language/_language-fr.yml#L98

@mcanouil @maelle What do you think of Tableau instead of Table ? 🤔

**Review by cderv — CHANGES_REQUESTED** [review]
Wrong file modified in this proposal

**Comment by mcanouil** [comment]
I think we already discussed this somewhere.

> according to common use.

A source? As far as I know, both are correct and are heavily used.
Since the language can be customised, I would not change anything here.

**Comment by cderv** [comment]
Thanks I forgot this discussion. 

Agreed on the breaking change. 

@famuvie are you aware you can change the translation ?

**Comment by famuvie** [comment]
> @famuvie are you aware you can change the translation ?

Yes, thank you.

If both alternatives are arguably valid, I'm fine with it. I just wanted to contribute a fix I keep having to do because my French collaborators keep _correcting_ this.

Sorry for missing the right file 🤷

**Comment by maelle** [comment]
I don't have any specific opinion but out of curiosity I went and looked at what Microsoft Office uses... Tableau apparently? https://support.microsoft.com/fr-fr/office/ins%C3%A9rer-un-tableau-a138f745-73ef-4879-b99a-2f3d38be612a

**Comment by famuvie** [comment]
> I don't have any specific opinion but out of curiosity I went and looked at what Microsoft Office uses... Tableau apparently? https://support.microsoft.com/fr-fr/office/ins%C3%A9rer-un-tableau-a138f745-73ef-4879-b99a-2f3d38be612a

That explains why my collaborators insist in using _Tableau_ 😂

**Comment by mcanouil** [comment]
Well, they actually use both

> Pour une table plus grande ou pour personnaliser un tableau, sélectionnez Insérer > tableau > Choisir une ligne et une colonne.

**Comment by cderv** [comment]
@famuvie thanks a lot for the feedback. 

FWIW I do think that this translation has also been made "Table" to match LaTeX which use also "Table" with french translation for babel; 

Considering it can be customized project-wise, and through custom extension, I don't think we'll change the default. 

Again thanks a lot for the feedback !

**Pull request closed without merging**
