### PR TITLE
Lua filter utils

### PR DESCRIPTION
**Pull request by jmbuhr**
this PR exports `quarto.base64` together with the already exported `quarto.utils` and `quarto.json` for use in lua filters. This is helpful for writing filters that can create self-contained htmls.

### CODE REVIEW

**Comment by jjallaire** [comment]
@cscheid I'm assuming that the addition to `.gitignore` is fine here?

@dragonstyle Are we okay with adding the `quarto.base64` module or should we consider re-organizing to e.g. `quarto.encoding.json`, `quarto.encoding.base64`. I'm personally fine with `quarto.base64` but just wanted to double-check with you.

**Comment by dragonstyle** [comment]
> @dragonstyle Are we okay with adding the `quarto.base64` module or should we consider re-organizing to e.g. `quarto.encoding.json`, `quarto.encoding.base64`. I'm personally fine with `quarto.base64` but just wanted to double-check with you.

I think this makes sense at the root level too, vs trying to next everything in namespaces. I'm good with `quarto.base64`

**Comment by cscheid** [comment]
@jjallaire yeah, that looks safe. I was under the impression that we only keep those now when the vendoring process fails _and_ we can't roll it back for whatever reason.

@jmbuhr Are you having issues with those files hanging onto your filesystem? Maybe we should open a separate gh issue to track.

**Comment by jmbuhr** [comment]
@cscheid Yes. So I assume these where supposed to be deleted during the cleanup steps.
These are the files that stick around:
```
$ ls src/vendor-2022-08-15 
cdn.skypack.dev  deno.land  import_map.json
```

**Comment by cscheid** [comment]
@jmbuhr It seems that we're rolling back on failure but not throwing away the old version on success. Thanks for catching that! I'll fix right away.

**Comment by cscheid** [comment]
I just pushed a change to `main` that cleans those up. We can keep the `.gitignore` addition, but it should no longer be necessary.

**Pull request merged**
