### PR TITLE
Update to pandoc 3.1.11 and typst 0.10.0

### LINKED ISSUE #7439: link-citation activated when suppress-bibliography is true throw a LaTeX compilation error due to missing citeproc command
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/7431

<div type='discussions-op-text'>

<sup>Originally posted by **cderv** October 31, 2023</sup>
I believe this is an issue with Pandoc itself. 

Take this example 
````markdown
---
title: test
references:
- type: article-journal
  id: WatsonCrick1953
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for
    deoxyribose nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  URL: https://www.nature.com/articles/171737a0
  language: en-GB
link-citations: true
suppress-bibliography: true
--- 

See @WatsonCrick1953 for additional discussion
````

Now render with 
````powershell
quarto pandoc -f markdown -t latex -s --citeproc -o test.pdf test.qmd
````
You will get the error; You could also do `-o test.tex` and look inside the file - there is no defintion of the `\citeproc` command. 

Remove `suppress-bibliography: true` and run 
```powershell
quarto pandoc -f markdown -t latex -s --citeproc -o test.tex test.qmd
```

The citation information from pandoc are correctly inserted
````tex
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
````

It comes from template https://github.com/jgm/pandoc/blob/d3d0406515cb6aae6f43e60dfa37014bdd91e79c/data/templates/default.latex#L337-L341

so somehow something deactivate the insertion. or did not change the use of 
````tex
(\citeproc{ref-WatsonCrick1953}{1953})
````

Running with Quarto 1.3 which has a different pandoc we see that the .tex is changed 
````tex
 (\protect\hyperlink{ref-WatsonCrick1953}{1953})
````

This means this is an issue between this two version of pandoc 

Doing a bit of bisecting with pandoc version, first one to fail is 3.1.7  (https://github.com/jgm/pandoc/releases/tag/3.1.7) 

They did some changes about LaTeX writer and citation linking. So possibly related. 

I'll open an issue upstream.  

</div>

### LINKED ISSUE #7584: svg device + `embed-resources: true` not working as expected
### Bug description

When I use an svg device with `self-contained: true`, the text in every plot (except the first) gets...wonky? See below for the basic code I am using.  This behavior also occurs when I use `embed-resources: true`, but *not* when I use `standalone: true`.

### Steps to reproduce

````qmd
---
title: "Untitled"
format: html
self-contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(dev='svg')
```

## Header

Text to start

```{r}
plot(0, 0, xlab = "hello")
legend("topright", legend = c("text here", "text there"))
```

some text inbetween

```{r}
plot(0, 0, xlab = "goodbye")
legend("topright", legend = c("text here", "text there"))
```
````

### Expected behavior

_No response_

### Actual behavior

quarto_ex

### Your environment

````md
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.1    tools_4.3.1       rstudioapi_0.15.0 knitr_1.43        xfun_0.39
````

### Quarto check output

```bash
$ quarto check
Quarto 1.4.504
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.504
      Path: C:\Users\alexc\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2023.01
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\alexc\AppData\Roaming\TinyTeX\bin\win32\
      Version: 2022

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.6.5
      Path: C:/Users/alexc/AppData/Local/Programs/Python/Python36/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/alexc/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.43
      rmarkdown: 2.24

[>] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by jjallaire**
@dragonstyle I did not do the reconciliation of templates (some latex and some typst)

@cderv IIRC we put in a workaround of some sort pending a typst update, so let's remove that if appropriate)

### CODE REVIEW

**Comment by cscheid** [comment]
> @cderv IIRC we put in a workaround of some sort pending a typst update, so let's remove that if appropriate)

Just FYI, If you're talking about the image sizing workaround, then my understanding is that the Pandoc fix for that doesn't currently solve the problem, so we need to keep that for a bit longer.

**Comment by cderv** [comment]
I did revert the change for the `Cite` fixup. Pandoc 3.1.10 does indeed solve this issue. 

I see we update to typst 1.10.0 - how do we know Pandoc is up to date to support recent change in Typst ? 

As a reminder about last time, change in Typst 1.9.0 did break stuff in Pandoc 3.1.9, which required the changes in Pandoc 3.1.10 to support Typst 3.1.9. 


@cscheid Pandoc 3.1.10 includes `toc-depth` support in the writer, the workaround from https://github.com/quarto-dev/quarto-cli/pull/7825 may not be needed. There is probably impact on template too (cc @dragonstyle)

It does also have fix for typst box 
* https://github.com/jgm/pandoc/issues/9104 

unless not enough
I think we have a workaround for this too: 
* https://github.com/quarto-dev/quarto-cli/pull/7019

I also see in Release note that Typst now support CSL (https://github.com/jgm/pandoc/pull/9186) - maybe there is some adjustment to do here for `csl` support 🤔 

I believe we have some adjustment to footnotes too (but I think @dragonstyle already aware) as `aside` will have `doc-footnote` now, possibly section be used instead of aside
> To conform to validator’s expectations, doc-footnote role is used with aside and doc-endnotes with section.

> aside is used only for notes at ends of sections or blocks; if all the notes come at the end of the document, section is used so we can have the doc-endnotes role.


Regarding issue to close

*  This PR will close https://github.com/quarto-dev/quarto-cli/issues/7584 as better svg handling for embeding is in Pandoc 3.1.10
* This PR will close https://github.com/quarto-dev/quarto-cli/issues/7439 (https://github.com/jgm/pandoc/issues/9163 merged)

**Comment by cscheid** [comment]
> I think we have a workaround for this too:
> 
> * [typst: wrap image with attributes in a Para with a `#box([])`.  #7019](https://github.com/quarto-dev/quarto-cli/pull/7019)

This is the workaround we shouldn't remove yet. If you read the full issue you'll see that the current Pandoc behavior is still not great. There's no full solution either way, but the workaround we allows for images to autosize well in some settings (which Pandoc's behavior _after the fix_  doesn't.)

**Comment by jjallaire** [comment]
John's release email noted that they updated to Typst 0.10: 

* Typst support has been updated to typst v0.10.0 (though support is only
  partial).  Typst can now use CSL styles for citations (specify `csl`
  in the metadata or as a variable when writing typst).

**Comment by cderv** [comment]
> noted that they updated to Typst 0.10:

How did I missed that  ! Great. Hopefully he will continue to add it to release note. 👍

**Comment by jjallaire** [comment]
I'm moving this out of draft (assuming that we've got the various pieces in place post update to typst and pandoc). Pandoc also just did a minor patch w/ bug fixes (3.1.11) which I went ahead and updated to. @dragonstyle Could you review and merge as appropriate once any additional pending work has landed?

**Comment by dragonstyle** [comment]
will do!

**Comment by dragonstyle** [comment]
The failing tests appear to be related to captions/typst - any chance you could have a quick look @cscheid ?

**Pull request merged**
