### PR TITLE
raw blocks is a portion of the ff matrix that is mostly an identity matrix

### PR DESCRIPTION
**Pull request by gordonwoodhull**
It's always going to be the case that there are some features which are only implemented for one format, and this is how it is for pass-through raw blocks.

It is also _possible_ that another format could support `{=mdx}`.

So we can remove the confusing "format feature" category, and move `mdx` into `raw-blocks`.

`{=latex}` is another identity, but `{=html}` works everywhere. 

(`{=html}` is not really a "raw" block, but we can worry about the nomenclature when there are other parsed and processed raw blocks.)

image

### CODE REVIEW

**Comment by cderv** [comment]
> but {=html} works everywhere.
>
> ({=html} is not really a "raw" block, but we can worry about the nomenclature when there are other parsed and processed raw blocks.)

This is true only for raw block with table input. We do look into and check if there is a HTML table, and then we do parse it **even when not requesting HTML output**. 

Usually raw block is an escaping mechanism where Pandoc will not parse as Markdown, and will output the raw block as is if the `--to` format matches the output (or a format support `+raw_html` for example). 

This is an interesting case because I don't see this Raw Blocks syntax as a Quarto feature for the matrix. I see the behavior with table as a Table feature only. 

If we start using raw attributes (inline or block) for specific feature (like new `{=pandoc-native}` for example), then this is a Quarto feature in the format matrix. 

Here is my current thoughts on this for discussion. Thanks a lot for all the work Gordon ! This is really valuable !

**Comment by gordonwoodhull** [comment]
For sure, there are many different valid ways to classify features. Hierarchies are always imperfect.

I'm just creating a folder for all features that use the "raw blocks" syntax, which is sometimes a pass-through and sometimes incurs other processing.

I just added `{=tex}`, which also works almost everywhere.

**Comment by gordonwoodhull** [comment]
I'm also fine with moving html-raw-blocks to the `table` category (which I'll create soon).

Really its a DAG with features belonging at many places in a hierarchy (and then interacting with other features argh). But we have to flatten it into a tree at least for now.

**Comment by cscheid** [comment]
> (and then interacting with other features argh)

I think we can make a decision not to worry about feature interaction in this matrix. While it is true that a number of our bugs arise from feature interactions, see eg https://github.com/quarto-dev/quarto-cli/issues/9155, I think we can decide that it's slightly out of scope here (this is a sufficiently big and valuable task by itself, we don't need to make it harder on ourselves).

**Comment by gordonwoodhull** [comment]
Feature interaction, where we need to consider it, is captured by multiple cases within a feature in the detailed view. 

(Currently only `fig-align` but I'm sure there are other places where this will be helpful.)

Thinking of the ff matrix as a process, rather than something to be completed, is really helpful. In my mind it is sort of a structured wiki, and something that will be helpful when we are ready to accept more contributions.

**Comment by cderv** [comment]
> I just added {=tex}, which works everywhere except Typst. 😱

About this, what is not working exactly ? The LaTeX math handling from raw LaTeX block ? You mean Pandoc just does not support it for typst, right ? 

My understanding is Pandoc has a specific feature where raw LaTeX will be transformed to HTML math if math is activated for HTML, and if latex raw block are a `\begin` environment for one of the supported environment. It is in HTML.hs in pandoc. 

I don't see it documented explicitly like this in the MANUAL though, nor associated to an extension. So it seems a specific HTML feature and it is not supported by typst in Pandoc itself, nor any other non HTML format;  

Just want to confirm I got it right, or if you are referring to another issue.

**Pull request merged**
