### PR TITLE
Fix placeholder image when multiple listing passed

### LINKED ISSUE #9845: image-placeholder ignored when more than one listing
### Bug description

If more than one listing is created for a page, and if the "image-placeholder" option is used for the listings, the image used as placeholder in all listings is the one for the first listing. Sometimes no image placeholder is shown, however I could not get a reproducible example of this case.

This issue may be related to #6447 and it's present in Quarto version 1.4.554.

### Steps to reproduce

Create a project and example folders and files:

```bash
quarto create project website mysite
cd mysite
mkdir posts tutorials things
```

Here is the project structure:

```
.
├── about.qmd
├── index.qmd
├── posts
│   └── post1.qmd
├── _quarto.yml
├── styles.css
├── things
│   └── thing1.qmd
└── tutorials
    └── tutorial1.qmd
```

Edit `index.qmd` so that it contains several listings using `image-placeholder`:
```{.qmd filename=index.qmd]
---
title: "Mysite"
listing:
  - id: posts
    contents: posts/*.qmd
    image-placeholder: https://quarto.org/quarto.png

  - id: tutorials
    contents: tutorials/*.qmd
    image-placeholder: https://quarto.org/docs/authoring/images/html-figure.png

  - id: things
    contents: things/*.qmd
    image-placeholder: https://quarto.org/docs/authoring/images/elephant-subfigures.png
---

:::{#posts}
:::

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

:::{#tutorials}
:::
```

Create example files:
`posts/post1.qmd`:

```qmd
---
title: 'Post 1'
---

Hello
```

`tutorials/tutorial1.qmd`:
```qmd
---
title: 'Tutorial'
---

# My tutorial
```

`things/thing1.qmd`:
```qmd
---
title: 'A thing'
---

# This is an example
```

### Expected behavior

Each listing element should display its corresponding image placeholder.

### Actual behavior

All listings display the image placeholder from the first listing:

bug

### Your environment

IDE: VIM - Vi IMproved 8.2
Operating system: Linux Xubuntu 22.04.3 LTS

### Quarto check output

_No response_

### PR DESCRIPTION
**Pull request by cderv**
This follows up on 3895a51d7cdbb0764423f8250f340131a72d1cde  to solve #6447, so that it fixes #9845

The fix was incomplete has the `image-placeholder` field could be defined per listing. 

Each listing can define a correct placeholder image and use this image for its posts. It will be correctly retrieved base on the unique listing.id.

This PR modifies what has been done in 3895a51d7cdbb0764423f8250f340131a72d1cde  by @dragonstyle to retrieve all placeholder content defined in listings and correctly choose the right one. 

For this, the listing id is now added to the placeholder commend we use. This assumes that `id` is always set, which I believe is true from the typse we use 
https://github.com/quarto-dev/quarto-cli/blob/c4294016ed67b4427680844dd5992182630b62b6/src/project/types/website/listing/website-listing-shared.ts#L134-L138
as output of our listing reading which this PR now use
https://github.com/quarto-dev/quarto-cli/blob/c4294016ed67b4427680844dd5992182630b62b6/src/project/types/website/listing/website-listing-read.ts#L326-L330

I added more tests for this, but we could tests listings even more

### CODE REVIEW

**Comment by cderv** [comment]
Diff for this PR is best seen with no whitespace change : https://github.com/quarto-dev/quarto-cli/pull/9851/files?diff=split&w=1

**Comment by cderv** [comment]
@cscheid @gordonwoodhull if any of you want to review. Just to be safe. This is really an improved version of https://github.com/quarto-dev/quarto-cli/commit/3895a51d7cdbb0764423f8250f340131a72d1cde to solve initally https://github.com/quarto-dev/quarto-cli/issues/6447, so that it now fixes https://github.com/quarto-dev/quarto-cli/issues/9845

I believe this is an ok-change before release, but better be safe with your review confirmation

**Comment by cscheid** [comment]
Passing that ID seems necessary, so this looks good to me.

**Comment by cderv** [comment]
Thank you !

**Pull request merged**
