### PR TITLE
`publish gh-pages` renders into clean directory

### PR DESCRIPTION
**Pull request by ijlyttle**
## Description

Fix #3199

I found that I needed to make the cleaning in a different place. I made the smallest change that I could, but I have a suspicion that the end result could be cleaner.

I see that you went to some trouble to pull `gh-pages` into a worktree, instead of creating an orphan branch. My guess is that, at one point, you wanted to add to `gh-pages`, perhaps along the lines of what pkgdown does to facilitate the `dev` directory to be added to an existing site.

Not my place to suggest what the "right" behavior is, but I thought I'd point out that this fix may leave in place some unnecessary infrastructure. That said, using the worktree *does* let you track changes in the branch.

I figured I should point it out, and give you all a chance to ask for further changes (or no further changes). 

Otherwise, I tested this on one of my repos; in this case, it works as advertised.

## Checklist

I have (if applicable):

- [x] filed a [contributor agreement](../CONTRIBUTING.md).
- [x] referenced the GitHub issue this PR closes
- [x] updated the appropriate changelog

### CODE REVIEW

**Comment by cscheid** [comment]
Thank you for the PR! We should probably check for the result of the process and report errors/bail if it fails. What happens if the site directory isn't there to begin with?

**Comment by ijlyttle** [comment]
This may not be answering the question you were asking, but `siteDir` seems to be a temporary directory named according to the hash of the `gh-pages` branch, e,g, `dea8187`.

As far as I can tell, `siteDir` will exist because the `gh-pages` branch exists. If `gh-pages` hadn't existed, I see logic to create an orphan `gh-pages` branch so that it does exist by the time it gets "there".

**Comment by cscheid** [comment]
Got it, and thank you! I just fundamentally misunderstood that code.

**Comment by cscheid** [comment]
Thank you for the contribution!

**Pull request merged**
