### PR TITLE
Update to Pandoc 3.1.5

### LINKED ISSUE #6015: docx table: set columns width seems not work
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/6006

<div type='discussions-op-text'>

<sup>Originally posted by **aborruso** June 22, 2023</sup>
### Description

Hi,
when I render this qmd, the columns width it not the one I have set. How to force it to be `50,30,20`?

I'm using quarto 1.4.43 in Debian 11.

````qmd
---
title: "UV2"
format:
  docx:
    toc: false
    number-sections: false
    highlight-style: github
    tbl-colwidths: [50,30,20]
---

# test


| Question | Reply | Note |
| --- | --- | --- |
|aMagna sint duis proident do. Laboris Lorem exercitation consectetur quis|a|b|
|aMagna sint duis proident do. Laboris Lorem exercitation consectetur quis|a|b|

````

image
</div>

### PR DESCRIPTION
**Pull request by jjallaire**
@dragonstyle Could you look at the template diffs and make whatever changes are implied by them to our templates?

@cscheid FYI that a Pandoc minor release is coming, probably worth testing proactively to make sure our new filter work isn't affected.

@cderv I believe this means we can remove a hack we put in for Typst (I don't recall the specifics but I do recall that we were doing something that we could back out when we took a Pandoc update. It looks like they made a bunch of improvements to Typst -- I'll dig into these early next week to make sure we still work correctly.

### CODE REVIEW

**Comment by jjallaire** [comment]
@cderv I believe that this failing test is right in the same area as the temporary change you made (using citeproc w/ typst): https://github.com/quarto-dev/quarto-cli/actions/runs/5492279090/jobs/10009614184#step:23:2677. Hopefully you will know the tweak we need to surmount this (perhaps just removing code we put in _until_ we were on a later version of pandoc?). Feel free to commit directly to this branch.

**Comment by dragonstyle** [comment]
@jjallaire just updated the pandoc template

**Comment by jjallaire** [comment]
I saw there was a change to `html.styles` as well, do we need a change for that?

**Comment by cscheid** [comment]
I just read over the changelog since 3.1.2, and I'm pasting here the entries that I think might affect us (crossref or otherwise)

```
  * AsciiDoc writer:

    + Make modern AsciiDoc the target for `asciidoc` (#8936).
      The AsciiDoc community now regards the dialect parsed by `asciidoctor`
      as the official AsciiDoc syntax, so it should be the target of our
      `asciidoc` format. The `asciidoc` output format now behaves like
      `asciidoctor` used to. `asciidoctor` is a deprecated synonynm. For
      the old `asciidoc` behavior (targeting the Python script),
      use `asciidoc_legacy`. The templates have been consolidated. Instead of
      separate `default.asciidoctor` and `default.asciidoc` templates, there
      is just `default.asciidoc`.
    + Text.Pandoc.Writers.AsciiDoc API changes:
      - `writeAsciiDoc` now behaves like `writeAsciiDoctor` used to.
      - `writeAsciiDoctor` is now a deprecated synonym for `writeAsciiDoc`.
      - New exported function `writeAsciiDocLegacy` behaves like
        `writeAsciDoc` used to.
    + Update line-through for asciidoc writer to custom inline style (#8933,
      Kevin Broch).

  * Typst writer:

    + Support `unlisted` class in headings (#8941).
    + Consolidate bibliography files into one `#bibliography` command (#8937).
    + Improve handling of autolinks (#8931).

  * Docx writer:

    + Make relative widths work in tables. This didn't work before because we
      were missing an attribute that tells Word to used fixed widths rather
      than computing optimal ones.

  * HTML reader: Update TableBody RowHeadColumns caculation (#8634,
    Ruqi). This change sets RowHeadColumns to the minimum value of each row,
    which gives better results in cases where rows have different numbers
    of leading th tags.

  * LaTeX writer: Fix escaping of `&` in `\href` and `\url` (#8903).

  * Docx writer:

    + Fix localization of "Abstract" title (#8702).
    + Allow `abstract-title` to be specified in docx metadata (#8794).

  * JATS reader:

    + Improve title and label parsing in the JATS reader (#8718,
      Noah Malmed.)
    + Add rowspan, colspan and alignment to cells in jats table
      reader (#8408, Noah Malmed)

  * LaTeX writer:

    + Fix width for multicolumn simple table (#8831).
```

**Comment by cderv** [comment]
> I believe this means we can remove a hack we put in for Typst (I don't recall the specifics but I do recall that we were doing something that we could back out when we took a Pandoc update. 

Indeed. This is now removed. We were setting a `citations` variable to deactivate some template part. This is done by Pandoc directly now when `+citations` is passed (the default for `--to typst`) 

Regarding the test, Pandoc adapted the syntax in 3.1.3 to use short syntax `<lab>` instead of `#label("lab")` so the regex in test was failing. This is now adapted. 

Should be all good now. I'll check that test is passing.

**Comment by jjallaire** [comment]
Thanks @cscheid for flagging those issues. I'm pretty sure we've got all of the asciidoc and typst issues covered. The other stuff looks like fixes / enhancements that should be transparent to us.

**Pull request merged**
