### PR TITLE
Typst: Move Pandoc interpolated variable from `typst-template.typ` to `typst-show.typ`

### LINKED ISSUE #10212: Typst: 1.6 introduces Pandoc interpolated variable to `typst-template.typ` rather than `typst-show.typ`
### Bug description

A change in [this commit ](https://github.com/quarto-dev/quarto-cli/commit/d40b8ec70e62245bc691aa9c3ca1eae1e6301c3b) introduces one Pandoc interpolated variable into `typst-template.typ`. While this is technically fine, as it really is a Pandoc template and valid code, this should probably be done in `typst-show.typ` with all other Pandoc variables. As a bonus, this is makes Typst LSPs angry, because it makes the Pandoc-ness more apparent, and makes editing Typst templates a bit messier.

Happy to PR in the minor changes necessary discussed below, if that's useful. I would have just opened a PR, but I didn't know if this was an intentional choice.

Finally, apologies if you view this more as a Feature Request as it *technically* isn't a bug, just a slightly off behavior. Happy to move to discussions if that's preferable.

### Steps to reproduce

Create a Typst format with
```bash
quarto create extension format:typst
```
And give it a name.

Line 64 of `typst-template.typ` now looks like below, which introduces a pandoc variable into the file.

```typst
    #text(weight: "semibold")[$labels.abstract$] #h(1em) #abstract
```

---

For testing completeness, this is just a document with an abstract, but any will do:

````qmd
---
title: Untitled
abstract: |
  Typst is a pretty cool way to produce PDFs. Currently the `typst-template.typ` 
  file has a single pandoc interpolted variable which could be a variable
  in `typst-show.typ` to let `typst-template.typ` play nice in Typst LSPs.
format:
  typtest-typst: default
---

## Introduction

*TODO* Create an example file that demonstrates the formatting and features of your format.

## More Information

You can learn more about creating custom Typst templates here: 

<https://quarto.org/docs/prerelease/1.4/typst.html#custom-formats>

````

### Expected behavior

All other partials introduce variables in `typst-show.typ`. I would expect to see:

In the article definition in `typst-template.typ`

```typst
  abstract: none,
  abstract-title: none,
  cols: 1,
```

Within the `article` body:

```typst
    #text(weight: "semibold")[#abstract-title] #h(1em) #abstract
```

In `typst-show.typ`:

```typst
$if(abstract)$
  abstract: [$abstract$],
  abstract-title: "$labels.abstract$",
$endif$
```

### Actual behavior

No variables in Typst are created, the Pandoc interpolated variable is dropped into the article definition like so:

```typst
    #text(weight: "semibold")[$labels.abstract$] #h(1em) #abstract
```

### Your environment

- IDE: RStudio
- OS: MacOS Sonoma 14.5
(Replicates on IDE: Positron / OS: Windows 11 as well, as this is tied to the template.)

### Quarto check output

```
Quarto 1.6.0
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.0
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/chris/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /usr/local/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library
      knitr: 1.46
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by christopherkenny**
## Description

One Pandoc variable was referenced in `typst-template.typ`. This moves it to the `typst-show.typ` file, adding a new variable to the `article` function call.

Closes #10212.

## Checklist

I have (if applicable):

- [x] filed a [contributor agreement](https://github.com/quarto-dev/quarto-cli/blob/main/CONTRIBUTING.md).
- [x] referenced the GitHub issue this PR closes
- [x] updated the appropriate changelog

### CODE REVIEW

**Comment by cscheid** [comment]
Since this means we honor `abstract-title` on `typst` now, we should change `src/resources/schema/document-attributes.yml` and rerun `quarto build-js` to get autocompletions to work.

**Comment by gordonwoodhull** [comment]
I don't think this changes any public interface. 

This is using metadata labels, the same mechanism for i18n in html:

https://quarto.org/docs/authoring/title-blocks.html#metadata-labels

**Comment by gordonwoodhull** [comment]
I've tested and I think we should merge and backport, to maintain the convention of referencing Pandoc variables / metadata only in `typst-show.typ`

**Comment by gordonwoodhull** [comment]
Ah, didn't see this at first, but now I see - yes my i18n changes in #9829 enabled `abstract-title` for Typst as a side-effect. We should reflect that in the schema. Will do!

**Comment by gordonwoodhull** [comment]
Merged to main, will backport now. Thanks @christopherkenny!

**Comment by cscheid** [comment]
@gordonwoodhull If you're at it, adding `abstract-title` to our feature-format matrix would be a good thing.

**Comment by gordonwoodhull** [comment]
Sure... I don't think we have entered any related features. Judging from the docs, I think this should go under

`feature-format-matrix/qmd-files/title-blocks/metadata-labels/`

**Pull request closed without merging**
