### PR TITLE
update to pandoc 2.19.1

### PR DESCRIPTION
**Pull request by benz0li**
## Description

Update to Pandoc 2.19.1

## Checklist

I have (if applicable):

- [ ] filed a [contributor agreement](../CONTRIBUTING.md).
- [ ] referenced the GitHub issue this PR closes
- [x] updated the appropriate changelog

### CODE REVIEW

**Comment by benz0li** [comment]
P.S.: File [contributor agreement](../CONTRIBUTING.md) is missing.

**Comment by jjallaire** [comment]
Thanks! I'll take care of this in a sec locally w/o merging the PR. For future reference info on contributing / agreements is now here: https://github.com/quarto-dev/quarto-cli/blob/main/CONTRIBUTING.md 

I'm not sure how that link to CONTRIBUTING.md in the PR got formed (I wonder if we have it in a template somewhere?) as it isn't actually the correct way to reference files in a GH repo.

**Comment by benz0li** [comment]
> I'm not sure how that link to CONTRIBUTING.md in the PR got formed (I wonder if we have it in a template somewhere?) as it isn't actually the correct way to reference files in a GH repo.

In addition, the following is auto-generated (above Description) when creating a pull request:

> Welcome to the quarto GitHub repo!
> 
> We are always happy to hear feedback from our users.
> 
> To file a _pull request_, please follow these instructions carefully: <https://yihui.org/issue/#bug-reports>
> 
> If you're a collaborator from outside `quarto-dev`, please make sure you have filed a [contributor agreement](../CONTRIBUTING.md).
> 
> Also, please complete and keep the checklist below.

I have deleted that part.

**Comment by jjallaire** [comment]
Okay, thanks. That it part of our template. Will resolve!

**Comment by cscheid** [comment]
(@jjallaire I added that, my fault. Clearly the path is being resolved wrong, sorry.)

**Pull request closed without merging**
