### PR TITLE
Fix issue with decorated code block when computation cell

### LINKED ISSUE #6917: Meta shortcode not resolved in DecoratedCodeBlock nodes
See https://quarto.org/docs/output-formats/hugo.html#configuration

image

The `meta` is defined in main doc: https://github.com/quarto-dev/quarto-web/blob/34a49a835a864fb81f6f0a5370e9b417e418859e/docs/output-formats/hugo.qmd#L3
and used in included file inside a code block : https://github.com/quarto-dev/quarto-web/blob/34a49a835a864fb81f6f0a5370e9b417e418859e/docs/output-formats/_ssg-workflow.qmd#L62-L74

It works when used in main text: https://quarto.org/docs/output-formats/hugo.html#workflow
https://github.com/quarto-dev/quarto-web/blob/34a49a835a864fb81f6f0a5370e9b417e418859e/docs/output-formats/_ssg-workflow.qmd#L7

@cscheid I understood this was something we fixed and should work already. Is that so ?

### LINKED ISSUE #6985: Error when using `filename` chunk option
### Bug description

When including an external file that contains code using the chunk option `file="whatever"` and using the `filename` chunk option to add a filename heading to the output, Quarto fails with this error:

```
Error running filter /Applications/quarto/share/filters/main.lua:
/Applications/quarto/share/filters/main.lua:10955: attempt to index a nil value (field 'convent')
```

### Steps to reproduce

Use these three files:

**r-things.R**

```r
# Here's some R code
plot(1:10)
```

**stan-things.stan**

```stan
// Here's some Stan code
data {
  int<lower=0> n;
}
```

**testing.qmd**:

````qmd
---
title: External file test
engine: knitr
---

Used to work in 1.3, now doesn't

```{r file="r-things.R", eval=FALSE, filename="r-things.R"}
```
````

### Expected behavior

It used to look like this:

image

But now it causes this error:

```
Error running filter /Applications/quarto/share/filters/main.lua:
/Applications/quarto/share/filters/main.lua:10955: attempt to index a nil value (field 'convent')
stack traceback:
	/Applications/quarto/share/filters/main.lua:2317: in function </Applications/quarto/share/filters/main.lua:2311>
	(...tail calls...)
	[C]: in ?
	[C]: in method 'walk'
	/Applications/quarto/share/filters/main.lua:148: in function </Applications/quarto/share/filters/main.lua:138>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:725: in local 'callback'
	/Applications/quarto/share/filters/main.lua:738: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:773: in function </Applications/quarto/share/filters/main.lua:770>
stack traceback:
	/Applications/quarto/share/filters/main.lua:148: in function </Applications/quarto/share/filters/main.lua:138>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:725: in local 'callback'
	/Applications/quarto/share/filters/main.lua:738: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:773: in function </Applications/quarto/share/filters/main.lua:770>
```

### Actual behavior

The error is not specific to R chunks—including Stan code like this also causes the same error:

````qmd
```{stan file="stan-things.stan", eval=FALSE, filename="stan-things.stan"}
```
````

---

The only workaround I've found is to not use a computational chunk or an external file. If I manually copy/paste the code from the external files and use chunk types with a `.` prefix, the filename works fine:

````qmd
```{.r filename="r-things.R"}
# Here's some R code
plot(1:10)
```

```{.stan filename="stan-things.stan"}
// Here's some Stan code
data {
  int<lower=0> n;
}
```

````

image

But any computational chunk with a filename attribute fails to render

### Your environment

- IDE: RStudio 2023.06.2+561
- OS: macOS Ventura 13.5.2

### Quarto check output

```
Quarto 1.4.376
[✓] Checking versions of quarto binary dependencies...
Pandoc version 3.1.8: OK
Dart Sass version 1.55.0: OK
Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
Version: 1.4.376
Path: /Applications/quarto/bin

[✓] Checking tools....................OK
TinyTeX: v2022.08
Chromium: (not installed)

[✓] Checking LaTeX....................OK
Using: TinyTex
Path: /Users/andrew/Library/TinyTeX/bin/universal-darwin
Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
Version: 3.11.3
Path: /opt/homebrew/opt/python@3.11/bin/python3.11
Jupyter: 5.3.0
Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
Version: 4.3.1
Path: /Library/Frameworks/R.framework/Resources
LibPaths:
  - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
knitr: 1.44
rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

### PR DESCRIPTION
**Pull request by cderv**
Fixes #6985

Just a small typo that caused an issue. 

@cscheid I am surprised this was not tested. Do you want to move the test in one of your crossref folder ?

### CODE REVIEW

**Comment by cscheid** [comment]
oof that's brutal, thank you.

Yes, I'm also surprised this wasn't tested, and we should create a regression test for it!

**Review by cscheid — COMMENTED** [review]
One easy way to test for this immediate regression is to add a block

```
_quarto:
  tests:
    html:
      ensureHtmlElements:
        - []
        - []
```

I don't remember the actual DOM off the top of my head, but it should be pretty easy for you to.

**Comment by cderv** [comment]
I added a test. But this is a variant of https://github.com/quarto-dev/quarto-cli/blob/main/tests/docs/crossrefs/before-newcrossref-regression-tests/knitr-filename.qmd which use only codeblock and not computation codeblock. 

I did not want to "touch" and update your crossref tests, but I am thinking this would be better to group with other than just a separated smoke-all doc.

**Comment by cderv** [comment]
Oh ok, I'll add that to the test (sorry I answered before reading your last comment)

**Comment by cscheid** [comment]
We can add this regression test right away and then more general tests after this is merged.

**Review by cderv — COMMENTED** [review]
It seems all good ! Thanks for the tweaks ! 

Feel free to merge yourself when ready.

**Comment by cscheid** [comment]
I'm going to merge this, and I _think_ it might fix the meta-in-decorated-code-block bug too.

**Pull request merged**
