### PR TITLE
Create _language-ca.yml

### PR DESCRIPTION
**Pull request by encosllo**
Catalan language

### CODE REVIEW

**Comment by cscheid** [comment]
Thank you for this contribution! Can you confirm you've sent us a [collaborator agreement](https://posit.co/wp-content/uploads/2023/04/2023-03-13_TC_Indiv_contrib_agreement.pdf)?

**Comment by cscheid** [comment]
Hm. I now realize we have an open PR with this contribution from a separate user, #5968.

**Comment by cscheid** [comment]
@encosllo I manually merged the two translations, and I generally took the earlier contribution over yours (but there's some you've added, so I kept them here!) If you can confirm you're ok with the changes and the collaborator agreement, I'll be happy to merge. Thanks again!

**Comment by encosllo** [comment]
@cscheid Thanks for merging the translations. I'm happy with it. The collaborator agreement has been already sent. Thanks!

**Comment by jmaspons** [comment]
Hi! I'm the one from the first PR for the Catalan translation. It seems that some strings have been lost in the merge (e.g. `section-title-abstract: "Resum"` https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language-ca.yml)

**Comment by jmaspons** [comment]
> Hi! I'm the one from the first PR for the Catalan translation. It seems that some strings have been lost in the merge (e.g. `section-title-abstract: "Resum"` https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language-ca.yml)

ping @encosllo @cscheid

**Comment by cscheid** [comment]
@jmaspons Thanks for catching that. I've restored those in the latest commit; a new release should be out shortly after.

**Comment by jmaspons** [comment]
Still some missing translations. I created a new PR #6531 @cscheid

**Pull request merged**
