### PR TITLE
ansi to typst demo

### PR DESCRIPTION
**Pull request by gordonwoodhull**
The implementation is terrible and has plenty of bugs, but I think this shows it is possible to translate ansi text coloring to typst.

I targeted emphatic's HTML raw blocks only. I guess error text would have to be put in raw blocks for formats such as Typst that support HTML translation.

The strategy is

1. Do what we do for tables but pull the content out of a `<pre>` and re-wrap it in a `<div>` because Pandoc will drop formatting on `<pre>` content.
2. Replace newlines with `<br />`s.
3. Replace spaces that are not inside tags with `&nbsp;`s.

(Is this all that a pre does? I'm not sure. I don't want to think about tabs, but I will.)

image

Some problems with this:
- Typst text does not have a background color, so it must be wrapped in a `#box()` and that box needs an inset to not look ugly. The inset causes vertical misalignment with surrounding text. There is probably a way to fix this.
- Monospace font is hard-coded. A [Typst raw block](https://typst.app/docs/reference/text/raw/) might be better, but it looks like that would be a completely different approach and not leverage Pandoc's Typst property output.
- Leading/spacing for `<br />`s is too big
- Typst seems to drop text elements containing only nbsps, as seen in the diff example

  Expected (screenshot of HTML output)

  image

  Actual (Typst)

  image

  Perhaps one of the other Unicode spaces would be retained, haven't tried.
- Span and div implementation is demo quality, haven't thought about implications of turning this on across all text.
- Better implementations probably exist of replacing spaces not inside tags.

### CODE REVIEW

**Comment by cscheid** [comment]
> Typst seems to drop text elements containing only nbsps, as seen in the diff example

From my understanding, @coolbutuseless is using related but slightly different tricks: https://github.com/coolbutuseless/emphatic/issues/12#issuecomment-2087817116

**Comment by coolbutuseless** [comment]
I'm at a distinct advantage with `emphatic` in that I have the raw unprocessed text and colour/fill information stored separately.    html-to-typst seems like a worthy goal for easily getting compatibility with existing output, but is (now) unnecessary for `emphatic` with the typst-backend I wrote yesterday.

Any markup-style language makes it easy to output colour tags wrapping the text - so ansi, latex, html and now typst output all follow the same general approach - with just some `if/then` to select the specific start/end tags etc.

For the `html` output from `emphatic` I'm happy to make changes which would make this a more useful test case for this approach.

**Comment by gordonwoodhull** [comment]
Completely agree - I have not tried it yet,  but emphatic will be able to create much more minimal and idiomatic Typst code than Quarto can via HTML translation. 

Emphatic's native Typst output should be the default option. 

I am using emphatic as a test case partly because it is simpler than some of the other places we want to use this technique (like in error handling). I've learned some nice techniques from your implementation which I will apply here,  like `\u{00a0}` and `#highlight` - thank you! 

We have to figure out where we want to do translation. I don't think it is all raw html blocks but it might be `<pre>` blocks that contain formatting or something like that.

**Comment by cscheid** [comment]
> I don't think it is all raw html blocks but it might be `<pre>` blocks that contain formatting or something like that.

Agreed - I was thinking something like `<div class="quarto-process-pre-nodes-as-ast"><pre>...</pre></div>` but with a less horrendous class name.

**Comment by gordonwoodhull** [comment]
`#highlight()` works better than `#box()` in terms of alignment and inset, and also fixes the space issue. (I was already using `&nbsp;` which is the same as `\u{00a0}`.)

**Comment by gordonwoodhull** [comment]
There is already `html-table-processing` so I'm going with `html-pre-tag-processing`.

It will be opt-in with `parse` at the div level, but also allowing opt-out at the meta level with `none`.

I will work up a demo using plain ansi2html but we should also figure out what else we want to enable it for.

It won't work until the Pandoc release, so I'll keep working on this in a branch.

**Pull request closed without merging**
