### PR TITLE
Listing Translation ES

### PR DESCRIPTION
**Pull request by dragonstyle**

### CODE REVIEW

**Comment by dragonstyle** [comment]
Hi @edgararuiz - if you have a few moments and would be willing, could you review these suggested translations for some new capabilities in Quarto (pinging you just because I see that you've contributed translations in the past)?

I'm happy to answer questions to provide context for the usage of these strings, or you can also check documentation for the feature here:

https://quarto.org/docs/websites/website-listings.html#overview

**Comment by edgararuiz** [comment]
```yaml
listing-page-order-by: "Ordenar por"
listing-page-order-by-default: "Pre-seleccionado"
listing-page-order-by-date-asc: "Más reciente"
listing-page-order-by-date-desc: "Menos reciente"
listing-page-order-by-number-desc: "Número alto a bajo"
listing-page-order-by-number-asc: "Número bajo a alto"
listing-page-field-date: "Fecha"
listing-page-field-title: "Título"
listing-page-field-description: "Descripción"
listing-page-field-author: "Autor"
listing-page-field-filename: "Nombre de Archivo"
listing-page-field-filemodified: "Fecha de modificación"
listing-page-field-subtitle: "Sub-título"
listing-page-field-readingtime: "Tiempo para completar lectura"
listing-page-field-categories: "Categorías"
listing-page-minutes-compact: "{0} minutos"
listing-page-category-all: "Todas"
listing-page-no-matches: "No hay resultados"
```

**Comment by edgararuiz** [comment]
@dragonstyle - Just posted a suggested translation, hope it helps!

**Comment by dragonstyle** [comment]
Thank you , it does very much!

**Pull request merged**
