### PR TITLE
Merge metadata instead of overriding

### LINKED ISSUE #11139: Quarto improperly merges metadata for Lua filter use

### PR DESCRIPTION
**Pull request by cscheid**
Closes #11139.

### CODE REVIEW

**Comment by cscheid** [comment]
This is going to be much harder than I thought.

**Comment by cderv** [comment]
As this part is about support inline execution in YAML metadata (which is what `engineMetadata` is about), we really need to be careful with merging to not endup with unproccessed meta. 

TBH, I more inclined to not support using inline computation in metadata as we support metadata block created from code cells in document. This would mean that this is whole code part about `engineMetadata` is unnecessary (but would be breaking anyone using it).

**Comment by cscheid** [comment]
The bug would also happen if metadata blocks created from code were doing complicated merges.

**Comment by cscheid** [comment]
I'm going to close this PR and we'll have to revisit in 1.7.

**Pull request closed without merging**
