### PR TITLE
Bugfix/9816

### LINKED ISSUE #9816: typst callouts are bracketed
Somehow #9690 caused Typst callouts to have an extra level of square brackets, which are rendered as text

image

Sample of Typst output for `dev-docs/feature-format-matrix/qmd-files/callout/document.qmd`:

```typst
#block[
#callout(
body: 
[
[
A callout does not need a title.

]
]
, 
title: 
[
[
Warning
]
]
, 
background_color: 
rgb("#fcefdc")
, 
icon_color: 
rgb("#EB9113")
, 
icon: 
fa-exclamation-triangle()
)
]
```

***Likely incorrect*** fix - I ran out of time for now and couldn't pinpoint why this is happening... I'm sure there is a better way to to fix this!

```diff
--- a/src/resources/filters/customnodes/callout.lua
+++ b/src/resources/filters/customnodes/callout.lua
@@ -391,8 +391,8 @@ function _callout_main()
     end
 
     local typst_callout = _quarto.format.typst.function_call("callout", { 
-      { "body", _quarto.format.typst.as_typst_content(callout.content) },
-      { "title", _quarto.format.typst.as_typst_content(title) },
+      { "body", callout.content },
+      { "title", title },
       { "background_color", pandoc.RawInline("typst", background_color) },
       { "icon_color", pandoc.RawInline("typst", icon_color) },
       { "icon", pandoc.RawInline("typst", "" .. icon .. "()")}
```

### PR DESCRIPTION
**Pull request by cscheid**
Closes #9816.

This will fail CI because `pdftotext` isn't installed, so that needs fixing.

### CODE REVIEW

**Comment by cderv** [comment]
Nice idea! 

Is this expected that the test passes on windows though ? 
https://github.com/quarto-dev/quarto-cli/actions/runs/9322596818/job/25664024228?pr=9827#step:27:987

**Comment by cscheid** [comment]
I'm surprised too! I read somewhere that pdftotext is installed with miktex; I wonder if tinytex also installs it?

**Comment by cderv** [comment]
Oh lets me check that ! highly possible !

**Comment by cderv** [comment]
So locally I need to install it at least. Otherwise, 
````
Failed to spawn 'pdftotext': program not found
````
But when I do have, it works ok. 

So it seems that somehow, `pdftotext` is on PATH in our CI. I will to know what brings it, so that we are not surprised when it breaks, but for now this is good new.

**Comment by cderv** [comment]
I have got the answer ! 

It is available with Git For Windows as part of mingw64 distribution 
````powershell
> gcm pdftotext

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pdftotext.exe                                      0.0.0.0    C:\Program Files\Git\mingw64\bin\pdftotext.exe
````

So it is found ! 

Though version available is 4.00 
````powershell
> pdftotext --version
pdftotext version 4.00
Copyright 1996-2017 Glyph & Cog, LLC
````

But as long as it works ok ! I think we should be good. 

If you prefer to be safe, installing as I mentioned in other thread will be the way to go. Just tells me

**Comment by cscheid** [comment]
This is good enough for me!

**Pull request merged**
