### PR TITLE
Handle Pandoc change in table classes

### LINKED ISSUE #10607: [pandoc 3.2.1] Check for change on table as odd / even / header classes have been removed
Change happened at 
- https://github.com/jgm/pandoc/commit/cd15313216c75e1ff3577da728172db9ff69a6b6

It caused issues with R Markdown 
- https://github.com/rstudio/rmarkdown/issues/2567
- https://github.com/rstudio/rmarkdown/issues/2566

It will be important to check this is not impact too much Quarto. We leverages the class in some places like 
https://github.com/quarto-dev/quarto-cli/blob/814604696f1a36c4351245100f72c7fb75fba5eb/src/format/html/format-html-bootstrap.ts#L453-L454

CSS will need to be updated to 
```css
thead tr { /* targets previous header class */ }
tbody tr:nth-child(2n) { /* targets previous even class*/ }
```

### LINKED ISSUE #10904: Markdown tables isn't formatted in newer Quarto versions
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/10902

<div type='discussions-op-text'>

<sup>Originally posted by **snhansen** September 27, 2024</sup>
### Description

I just noticed that markdown tables suddenly doesn't have any formatting done. Is this intentional? The reason I'm asking is because it's how (most of the) tables are presented in the documentation, see e.g. https://quarto.org/docs/authoring/tables.html#markdown-tables

This example from the documentation

```
| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

: My Caption {#tbl-letters}

See @tbl-letters.
```

renders like this for me:

image
</div>

### LINKED ISSUE #10907: Something wonky is going on with the tables listing the project options
### What would you like to do?

Report an issue on quarto.org

### Description

If you go to this page: https://quarto.org/docs/reference/projects/options.html and look at the tables showing the options and descriptions of those options, the table is all wonky and not formatted correctly. It looks like the CSS vertical alignment between table column 1 (the options) and table column 2 (the description) are middle aligned vs top aligned. The result makes it look really not aligned properly and is difficult to read (e.g. the description for `type` looks like it is for both `type` and `title`).

### PR DESCRIPTION
**Pull request by cderv**
Fix https://github.com/quarto-dev/quarto-cli/issues/10904 
Close https://github.com/quarto-dev/quarto-cli/issues/10607

This reverts part of commit dd6717f.

The `.table` is set by quarto itself and its removal in html output is a sign that something has changed and it is not set correctly anymore.

We restore original test to correctly fix this.

See details explanation of current situation at 
- https://github.com/quarto-dev/quarto-cli/issues/10904#issuecomment-2378959876

Opening this PR as a draft with first idea to put back the odd, even and header class on tables that are parsed directly by Pandoc. 

We could also find other solution with new approach to serve the same purpose (identifying pandoc's table to style them)

This PR includes snapshot test with playwright so that we can detect next time when the look of the tables are changing. 

(BTW this is a first version of snapshot testing with playwright - it could be quite heavy to commit each png, so we could also have something different by leveraging caching in CI: (1) git ignore the `__screenshot__` folder, and (2) cache it on CI so that each news runs can access the snapshot. )

### CODE REVIEW

**Comment by cderv** [comment]
Test passes locally. But I should have guessed that first try with this feature would not work on CI. Probably this need to be OS specific. 
Or even environment specific and so using caching on CI method only. 

I'll debug this.

**Comment by cscheid** [comment]
We need to have a longer conversation about this. The filter you suggested is a good idea, except (as I understand it) that it will trigger on _all_ tables, not just those that Pandoc itself parsed, and that is a problem with (eg) our html table processing.

**Comment by cderv** [comment]
> The filter you suggested is a good idea, except (as I understand it) that it will trigger on all tables, not just those that Pandoc itself parsed, and that is a problem with (eg) our html table processing.

Then it is on me and my incorrect understanding of how our filter chain works. I specifically added early in normalize step so that it applies first in AST for any `Table` parsed by Pandoc, and I paid attention to place this filter specifically before the HTML parsing we do. If this is not what it will do (I did not check yet other tables), then I think I don't understand completely the different layers of the filter chain and its ordering. 

To be clear, my intention is to apply specifically on Pandoc parsed Table only, and avoid our parsed HTML table.  

And I did as a draft so that we have a base to discuss on. So 💯 for discussion. 👍

**Comment by cscheid** [comment]
> I specifically added early in normalize step so that it applies first in AST for any Table parsed by Pandoc, and I paid attention to place this filter specifically before the HTML parsing we do

Nope, that's on me, I wrote too fast!

**Comment by cderv** [comment]
Regarding visual testing with playwright, it requires an update in our GHA workflows so that we can have working tests. Right now, it works locally but we have pixels differences between local and CI, even on same OS (linux for example). 

So I'll handle the update of CI in another workflow. Maybe it will be easier to run playwright tests, out of smoke-all runs and parallel testing to simplify the conditional and configuration.

**Comment by cderv** [comment]
@cscheid following our call, I have updated to do the change as HTML fixup in post render to match more closely previous Pandoc's behavior

**Comment by cscheid** [comment]
This is excellent too.

**Pull request merged**
