### PR TITLE
Don’t escape HTML in item.text

### LINKED ISSUE #5231: HTML incorrectly escaped in sidebar text
Regression occurred here:

https://github.com/quarto-dev/quarto-cli/commit/6dcadb85d19dbee547f8baaec45b7b9f1dd16a99

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/5221

<div type='discussions-op-text'>

<sup>Originally posted by **JavOrraca** April 17, 2023</sup>
I maintain the Southern California R User Group website ([socalr.org](https://socalr.org/)) which was developed with Quarto. I attempted to upgrade to Quarto 1.3.306 but raw HTML was not rendering as expected in the site's sidebar. For reference, our GitHub repo can be found here: [github.com/socalrug/socalr.org](https://github.com/socalrug/socalr.org)

Below an example code snippet from the `_quarto.yml` showing the raw HTML links in the `text` field under `contents`. Please advise if I should plan to update the project's `_quarto.yml` to work correctly with Quarto 1.3.306. Any pointers would be appreciated, thanks! 🙏

```
  sidebar:
    background: "#3469B6"
    logo: "images/logo_text_blue_background.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/socalrug
        text: GitHub
      - icon: slack
        href: https://socalrug.slack.com/
        text: Slack
      - icon: linkedin
        href: https://www.linkedin.com/company/socalrug/
        text: LinkedIn
      - icon: twitter
        href: https://twitter.com/oc_rug
        text: "Twitter: @oc_rug"
      - icon: instagram
        href: https://www.instagram.com/socalrug/
        text: "Instagram: @socalrug"
      - icon: youtube
        href: https://www.youtube.com/@SouthernCaliforniaRUsersGroup
        text: YouTube
      - icon: envelope
        href: "mailto:orangecounty.rug@gmail.com"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: '<a href="https://www.meetup.com/socal-rug/" target="_blank">Join our Meetups</a>'
      - href: index.qmd
        text: Events
      - text: '<a href="https://github.com/socalrug/presentations" target="_blank">Past Presentations</a>'
      - section: "Hackathons"
        contents:
          - text: '<a href="https://github.com/socalrug/hackathon-2022-04" target="_blank">2022-04</a>'
          - text: '<a href="https://github.com/socalrug/hackathon-2021-04" target="_blank">2021-04</a>'
          - text: '<a href="https://github.com/socalrug/hackathon-2020-04" target="_blank">2020-04</a>'
          - text: '<a href="https://github.com/socalrug/hackathon-2019-11" target="_blank">2019-11</a>'
          - text: '<a href="https://github.com/socalrug/hackathon-2019-05" target="_blank">2019-05</a>'
      - section: "Book Clubs"
        contents:
          - text: '<a href="https://www.meetup.com/socal-rug/events/290821300/" target="_blank">2023-01: Advanced Probabilistic ML</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/284913426/" target="_blank">2022-04: Forecasting Principles and Practice</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/283044538/" target="_blank">2022-01: Information Rules</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/280319522/" target="_blank">2021-09: Introduction to Statistical Learning</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/278765369/" target="_blank">2021-07: OpenIntro Statistics</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/278831056/" target="_blank">2021-07: Communicating with Data</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/276575373/" target="_blank">2021-03: Text Mining with R</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/275783285/" target="_blank">2021-02: Mastering Spark with R</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/275719547/" target="_blank">2021-01: R for Data Science</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/272034792/" target="_blank">2020-09: Advanced R</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/270076542/" target="_blank">2020-05: Applied Predictive Modeling</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/268226879/" target="_blank">2020-02: Feature Engineering & Selection</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/266912350/" target="_blank">2020-01: R for Data Science</a>'
```</div>

### PR DESCRIPTION
**Pull request by dragonstyle**
A regression in Quarto 1.3 where sidebar `item.text` specified in `_quarto.yml` previously wasn't HTML escaped when rendered and now is being HTML escaped. Regression introduced when adding supporting for icons in the sidebar approx 2 months ago :(.

Test added...

Fixes #5231

### CODE REVIEW

**Comment by cscheid** [comment]
If it's a regression then we definitely should fix, no question about it.

In a perfect world, though, these would be raw html blocks and we would be sending the content through our markdown pipeline, right?

**Comment by dragonstyle** [comment]
The way we're dealing with markdown in sidebars is kind of yucky. Would be a good thing to do better with in the future.

**Comment by dragonstyle** [comment]
> If it's a regression then we definitely should fix, no question about it.
> 
> In a perfect world, though, these would be raw html blocks and we would be sending the content through our markdown pipeline, right?

Y it is - when I added the support for icons, I changed `<%-`  to `<%=` - I'm not really sure why.

**Review by cscheid — APPROVED** [review]
This looks like the fix with the smallest blast radius, so it LGTM. But, for completeness's sake:

1) what else does this affect? escaping vs unescaping is always finicky
2) are we making this mistake elsewhere in the 1.2 -> 1.3 changes?

**Comment by dragonstyle** [comment]
> This looks like the fix with the smallest blast radius, so it LGTM. But, for completeness's sake:
> 
> 1. what else does this affect? escaping vs unescaping is always finicky

This will effectively restore the behavior to be the pre-2 months ago behavior, so you're right that there is likely some cases that are weird, but they will at least be weird in the old way (versus now). This is output into the body of the HTML document, so this should not result in things such as HTML elements appearing unencoded in attributes, etc...


> 2. are we making this mistake elsewhere in the 1.2 -> 1.3 changes?

Yes, there are places in the same commit that caused this issue have the identical problem (regressions introduced there)! Thank you for asking...

**Comment by dragonstyle** [comment]
I just pushed an update to this PR which effectively reverts _all_ the incorrect escaping for text that I introduced in the previous commit. Clearly I inverted my usage of `-` vs `=` in that commit resulting in this issue.

**Pull request merged**
