### PR TITLE
correctly split table from larger html content

### PR DESCRIPTION
**Pull request by cscheid**
Fixes issue reported in #4073

### CODE REVIEW

**Comment by aborruso** [comment]
Thank you very much @cscheid!!

Do you plan to release a pre release soon?

**Comment by aisligrace** [comment]
hi @cscheid thank you for the fix - as i was experiencing a similar issue. i tried reinstalling quarto but that didn't do the trick - do i need to do something special for this change to take effect? 

thanks!

**Comment by cscheid** [comment]
@aisligrace If you install [this version](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.3.129), the bug should be fix. If not, then I haven't actually fixed the bug! In that case, I'd love it if you could provide a simple example that doesn't work for you, and then feel free to reopen this issue as well.

**Comment by aisligrace** [comment]
@cscheid NVM - i installed that version and it worked perfectly! thank you so much for your quick fix and response - i sincerely appreciate it.

**Pull request merged**
