### PR TITLE
Inline code execution for Jupyter 

### LINKED ISSUE #5401: Inline Python variable rendering
Hi, we are looking at using Quarto but the ability to render Python variables into markdown text, using something similar to the `` `r variable` `` syntax is very important for us, as we have lots of titles and captions with auto-updating dates. Unfortunately, per [this recent comment](https://community.rstudio.com/t/how-can-i-use-inline-code-in-a-quarto-document/160575/3), it's not currently possible.

Is this on the roadmap, or are there any recommended workarounds? (shortcodes don't seem to be a good option because the variables are computed at runtime)

### PR DESCRIPTION
**Pull request by jjallaire**
This PR implements support for inline code execution in the Jupyter engine using inline code with an engine prefix. For example:

````markdown
```{python}
x = 25
```

The value is `{python} x`.
````

For consistency, this syntax is also now available for R. For example, the following are equivalent:

````markdown
The threshold level is`r x`.
The threshold level is`{r} x`.
````

We also need to implement this for OJS (cc @cscheid).

Closes #5401. See #1520 and #3570 as well.

### CODE REVIEW

**Comment by cscheid** [comment]
I settled on an easier version of the code, with two separate code paths. It turns out that the strings from Jupyter _and_ knitr come unmapped anyway, so the mapped version is not needed there. We only benefit from mapping in the OJS engine (because that's pure TS).

I also added minimal tests for the syntax in both jupyter and knitr engines. We probably should exercise the corner cases of this new syntax a little more strongly.

**Review by cscheid — APPROVED** [review]
LGTM, this is going to be a popular one!

**Comment by drpedapati** [comment]
Using Quatro version 1.4.226 (pandoc 3.1.5) distributed with mac build quarto-1.4.226-macos.pkg I don't see the expected functionality (Python 3.10.12). I am using:
ipykernel                 6.15.0             pyh736e0ef_0    conda-forge
ipython                   8.14.0             pyhd1c38e8_0    conda-forge
jupyter_client            8.3.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0           py310hca03da5_0  

Reproducible code:

```{python}
#| echo: false
#| include: false

x=25
summary = summarize_data()

```

The value is `{python} x`.

Output is simply rendered markdown

The value is `{python} x`.

with no value.

Thanks

**Comment by cscheid** [comment]
(In the future, please include the entire file, not just the snippet you believe is causing the problem.)

With that said, I'm pretty sure the issue you're encountering is that you're not declaring `engine: jupyter`, which is a necessary line for Python code.

**Comment by drpedapati** [comment]
Figured it out - leaving tips for other python vscode users:

1. YAML header cell must be marked as "raw" cell_type by clicking in the bottom right corner
2. I didn't use `engine: jupyter`, but `jupyter: python3` as in the [prerelease notes] (https://quarto.org/docs/prerelease/1.4/inline.html) [both seem to work]
3. Code execution must be on in the header:
`execute:`
  `   enabled: true`

Thanks
[p110_data_cleaning.ipynb.zip](https://github.com/quarto-dev/quarto-cli/files/12064158/p110_data_cleaning.ipynb.zip)

**Comment by cscheid** [comment]
> Code execution must be on in the header

Just to clarify: this behavior is [well documented](https://quarto.org/docs/projects/code-execution.html#notebooks). By default, quarto will not execute code in `.ipynb` notebooks. Those files tend to be used as the store of intermediate results as it often happens in cloud environments.

This discrepancy is another example of why we ask users to provide _exactly_ the input they used, instead of what they think caused the problem.

**Comment by rogerjbos** [comment]
Could someone please post a working example, or tell me what I am doing wrong?  The rendered output just shows the text rather than replacing the code with the python value.
```
---
title: "Python HTML Example"
engine: jupyter
format:
  html:
    theme: yeti
execute:
 enabled: true
---

```{python}
#| echo: false
chain = 'xyz'
start_date = '2023-07-01'
end_date = '2023-07-31' 
```
In the last month `{python} chain` had an start date of `{python} start_date` and end date of `{python} end_date`.

```

**Comment by jjallaire** [comment]
Your example is correct. Note that this requires the pre-release version of Quarto (see the note at the top of the docs for the download link): https://quarto.org/docs/prerelease/1.4/inline.html

**Comment by spider-z3r0** [comment]
Just popping in to say that this is a brilliant addition to quarto and has finally allowed me to just move over to quarto documents altogether. 

Just a note (which is probably stupid to people smarter than me) but I've found that this will only work if I render the document while my python venv is active, even if I point to the venv earlier in the set up). 

Thanks a million and I hope this helps someone.

**Comment by TaiPhamD** [comment]
If I have a python variable that is a mark down string. Is there a way to expand the python variable so it gets rendered as markdown?

for example

```{python}
my_string = '**Hello world**'
```

`{python} my_string` just renders it as literally text string but not markdown

I've tried

`!expr {python} my_string` but it doesn't work

**Comment by cscheid** [comment]
Docs: https://quarto.org/docs/computations/inline-code.html#markdown-output

**Pull request merged**
