### PR TITLE
errors: explicitly `Deno.exit(1)` when CommandError is caught at top-level

### LINKED ISSUE #10295: Wrong error code sent when failure
This is an error 
```
> quarto rend
ERROR: Unknown command "rend". Did you mean command "render"?
```
But exit code is `0` not `1`
````
> $LASTEXITCODE
0
````

This is a regression compared to previous version, and especially annoying when combine with `--quiet`
````
> quarto rend --quiet
> $LASTEXITCODE
0
````
There is now no way to check for error when `--quiet` is set. 

This was found as it broke a test in **quarto** R 📦 which rely on the exit code to know if there is an error or not. 

A quick `git bisect` points to 94c83b4b9d1d5265e2de77d4fd21a5f278df580b from 
- https://github.com/quarto-dev/quarto-cli/pull/9870 to solve https://github.com/quarto-dev/quarto-cli/issues/9032

I do believe the exist code should still be `1` as these are error. 

### Same on bash with latest stable build and pre-release

````
❯ $(qvm path versions)"/v1.5.54/bin/quarto" rend
ERROR: Unknown command "rend". Did you mean command "render"?

quarto-cli on  main [?⇡] via 🦕 via 🐍 v3.11.6
❯ echo $?
0
````

Latest working version for this is 1.5.40

### PR DESCRIPTION
**Pull request by cscheid**
Closes #10295.

### CODE REVIEW

**Comment by cscheid** [comment]
I've already backported this to v1.5: https://github.com/quarto-dev/quarto-cli/commit/f3b604f3f1dbb12252a71720377ff7a3992b7b44

**Comment by cderv** [comment]
Is it ok to build a new 1.6 later today so that the issue is fixed for quarto R package using prerelease ?

**Comment by cscheid** [comment]
Yes, for sure. (It should be safe to build a new prerelease at any point of `main`!)

**Comment by cderv** [comment]
Great. I'll trigger one. 

We'll need a new patch release too... It seems they update Quarto on CRAN already with the version having the bug... :( 

So now I get CRAN check error: https://cran.r-project.org/web/checks/check_results_quarto.html

A new 1.5 patch release would be good to help fix that.

**Pull request merged**
