### PR TITLE
extensions - canonicalize to array, process post-render scripts

### PR DESCRIPTION
**Pull request by cscheid**
Towards #9948.

### CODE REVIEW

**Comment by cscheid** [comment]
@andrewpbray This PR will change the way you do your metadata extension. We will now have a `metadata` field in `contributes`, and that field contributes metadata that will just be directly merged onto documents (for single-file renders) or projects (for project renders).

We need to do it in this way to avoid an issue with metadata ambiguity in custom project types in extensions.

**Comment by cscheid** [comment]
GitHub actions is currently [broken](https://www.githubstatus.com/incidents/lfrlwdg67fn8) but the syntax looks like this example:

https://github.com/quarto-dev/quarto-cli/pull/9953/files#diff-91c7093219d265413f6b8d8c71a99297c903cd1e6064375671071c77a137cc05

**Comment by andrewpbray** [comment]
Thanks for the heads up! This change makes sense.

**Comment by cderv** [comment]
Thanks Carlos !

**Comment by andrewpbray** [comment]
@cscheid just so I understand this change: will I change [this](https://github.com/qmd-lab/scheduled-docs/blob/main/_extensions/scheduled-docs/_extension.yml)

```yaml
contributes:
  project:
    project:
      pre-render:
        - run-scheduled-docs.ts
      post-render:
        - clean-scheduled-docs.ts
    metadata-files:
      - "scheduled-docs_files/draft-list.yml"
```

to this?

```yaml
contributes:
  metadata:
    project:
      pre-render:
        - run-scheduled-docs.ts
      post-render:
        - clean-scheduled-docs.ts
    metadata-files:
      - "scheduled-docs_files/draft-list.yml"
```

I just tried this with the version currently on quarto.org (1.5.45) but it no longer runs those scripts on `quarto render`.

**Comment by cscheid** [comment]
```
    metadata-files:
      - "scheduled-docs_files/draft-list.yml"
```

This will not work yet, see https://prerelease.quarto.org/docs/extensions/metadata.html

But it looks like the rest should work. Can you share a full example? We have a test in `tests/docs/project/prepost/extension` that has a very similar example and passes tests, so we need to figure out what's going on.

**Comment by andrewpbray** [comment]
Ah, I didn't see you'd already gotten docs up - great.

I saw your test there and I just copied and pasted into my extension.yml. Here's the extension that I'm working on:

[https://github.com/qmd-lab/scheduled-docs/blob/main/_extensions/scheduled-docs/_extension.yml](https://github.com/qmd-lab/scheduled-docs/blob/main/_extensions/scheduled-docs/_extension.yml)

Let me do some troubleshooting here and I'll report back.

**Comment by andrewpbray** [comment]
Here's a minimal website with a minimal script extension that I can't get to work:

https://github.com/andrewpbray/test-metadata-ext

The extension here contributes:

```yaml
contributes:
  metadata:
    project:
      pre-render:
        - check-pre-render.ts
      post-render:
        - check-post-render.ts
```

And rendering the website...

```bash
(base) MacBookPro:script-extension andrewbray$ quarto render
[1/2] index.qmd
[2/2] about.qmd

Output created: _site/index.html

(base) MacBookPro:script-extension andrewbray$ quarto --version
1.5.45
```
If instead you hard-code the links to the scripts in `_quarto.yml`:

```bash
(base) MacBookPro:script-extension andrewbray$ quarto render
_extensions/test-scripts/check-pre-render.ts
>>> Pre-render is working

[1/2] index.qmd
[2/2] about.qmd

_extensions/test-scripts/check-post-render.ts
>>> Post-render is working

Output created: _site/index.html
```

**Comment by cscheid** [comment]
Well, this is unlucky/embarrassing. 

1. The test I added isn't actually properly checking anything
2. Locally, it _seemed_ like the test was working, but that only happened because my working tree had a spurious extra directory with an additional copy of the extension, precisely in the wrong location that would trigger the pre-render scripts to run.

**Comment by cscheid** [comment]
@andrewpbray, with the latest fix:

````
quarto rendera$ 
/Users/cscheid/Desktop/daily-log/2024/06/21/test-metadata-ext/_extensions/test-scripts/check-pre-render.ts
>>> Pre-render is working

[1/2] index.qmd
[2/2] about.qmd

/Users/cscheid/Desktop/daily-log/2024/06/21/test-metadata-ext/_extensions/test-scripts/check-post-render.ts
>>> Post-render is working

Output created: _site/index.html
````

**Comment by andrewpbray** [comment]
😄 I've been there!

Looks great - thanks!

**Pull request merged**
