### PR TITLE
Add rel attribute to navitem links

### LINKED ISSUE #3212: rel="me" verification on About page links
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3207

<div type='discussions-op-text'>

<sup>Originally posted by **obrl-soil** November  7, 2022</sup>
Having recently started a Mastodon account, I see there's an option to help 'verify' one's account against one or more external websites, described in the [docs here](https://docs.joinmastodon.org/user/profile/) and more generally [here](http://microformats.org/wiki/rel-me), with results that look [like this](https://mastodon.social/@Mastodon). tl;dr one adds `rel="me"` to the `<a></a>` tag when linking to one's Mastodon profile from elsewhere.

I'm not sure how to do this on my blog's About page except by editing the HTML immediately after rendering the site and before pushing it to GH pages [like this](https://github.com/obrl-soil/obrl-soil.github.io/commit/7aeb06aaf977df0edc35b2a2eb58da9f76de6afb).

Would it be possible to add an attribute to the yml in `about.qmd` to help automate this? e.g.

 ```
 links:
    - icon: mastodon
      aria-label: Mastodon
      href: https://mastodon.social/@yourhandle
      rel: "me"
```
 
There are other variations I've seen like `rel="me nofollow"` that may also need be handled.</div>

### PR DESCRIPTION
**Pull request by effigies**
## Description

This PR adds a `rel` attribute to navigation items, e.g.,

````yaml
  navbar:
    right:
      - icon: github
        href: https://github.com/effigies
        rel: me
````

This will render as:

```HTML
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/effigies" rel="me"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>
```

If omitted, it renders as `rel=""` as below:

```HTML
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/effigies" rel=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>
```

To the best of my understanding, the `rel` attribute is a space-separated list, so an empty string is a sensible default and we don't need to add `if/else` machinery to handle this case. I can confirm that links work as expected.

To test locally, I needed to run `quarto build-js`. I committed the results, but let me know if I should remove that commit from the PR.

Closes #3212.

## Checklist

I have (if applicable):

- [x] filed a [contributor agreement](../CONTRIBUTING.md).
- [x] referenced the GitHub issue this PR closes
- [x] updated the appropriate changelog

### CODE REVIEW

**Comment by cscheid** [comment]
Thank you for the contribution! This looks good to me. We've had requests about this because of Mastodon (I suspect that's your usecase as well!).

I don't quite understand why GH didn't run our test suite on CI, but I'd like to make sure everything is clean first, but looking forward to merging this.

**Comment by cscheid** [comment]
It looks like we also need to update the about template: https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/projects/website/about/_links.ejs.html. @effigies do you want to give that a shot?

**Comment by effigies** [comment]
Done. Not quite sure what the difference is between `<%-` and `<%=`. Followed the apparent convention of each file.

**Comment by cscheid** [comment]
> Not quite sure what the difference is between `<%-` and `<%=`.

The `=` syntax escapes the content, and the `-` doesn't. But most of these should be `=`, which means what you're seeing is a separate (as we just discovered) widespread misuse of `-`, which we're fixing right away. But that's not your fault, so let me just merge this one as is.

Thank you so much for your contributions!

**Comment by effigies** [comment]
@cscheid @dragonstyle Would this be a reasonable thing to backport to the v1.2 branch? I'm not sure what your release process/philosophy is. For what it's worth, this rebases cleanly.

**Comment by dragonstyle** [comment]
In general, we are trying to create stable releases once we have marked a version as a 'real' release, so we don't generally back port fixes unless we feel like it is a critical fix with manageable regression risk. Given that criteria, to me this one doesn't feel like it makes the cut.

We do work hard to make our pre-releases sufficiently stable that users can safely use them (though of course they are not as stable as our full releases), so I'm hopeful many users could get this new capability via 1.3.

**Comment by giabaio** [comment]
Can I quickly follow up on this? Would it make sense to also add a `target` tag to allow for links (eg from the navbar) to be opened in a new tab? I've opened a [discussion](https://github.com/quarto-dev/quarto-cli/discussions/3541) on this, to explain the issue, but I think this would be an even better place? Thanks!

**Pull request merged**
