### PR TITLE
Support more table environment configuration for cross referencing

### LINKED ISSUE #924: Issues using {gt} objects as cross-referenced tables
I'm trying to incorporate a {gt} object as a table in a Quarto .qmd document that outputs to PDF.

When I try to add a table caption within a code chunk (using #| tbl-cap: xyz), I get the following error:

> **Package array Error:  Illegal pream-token (\caption): `c' used.**
> 
> **See the array package documentation for explanation.**
> **Type  H <return>  for immediate help.**
>  **...**                                              
>                                                   
> **l.252 \caption**
>               **{\label{tbl-test}Results }** 
> 
> **see Untitled.log for more information.**

This error occurs whether I try to output the {gt} object using only `gt()` AND if I use `as_latex()` afterwards.

Here's a test document:

---
title: "Untitled"
format: pdf
---

## Libraries

```{r}
library(tidyverse)
library(gt)
```

## Fake Data

```{r}
test_data <- tribble( ~a, ~b,
                      1, 2,
                      3, 4,
                      5, 6
)
```

## Table Output

```{r}
#| label: tbl-test
#| tbl-cap: "Results"


test_data |> gt()
```

## Cross-reference

@tbl-test

### PR DESCRIPTION
**Pull request by cderv**
This fixes #924 

As shown in https://github.com/quarto-dev/quarto-cli/issues/924#issuecomment-1131459922, the issue is that the raw LaTeX for caption is not inserted in the right place when option for the table environment are passed: https://fr.overleaf.com/learn/latex/Tables#Reference_guide

Issue happens with **gt** because it adds something like  `\begin{longtable}{rr}` and it needs to be matched in our script. 

Also we need to add LaTeX new line after the caption to avoid a no align error. In **knitr**, we are adding `\\` but I believe in Quarto you may expect `\tabularnewline` - I have seen this in here: 
https://github.com/quarto-dev/quarto-cli/blob/97b69958010cc5321b2e8d688d189b2a7d52d9f0/src/format/pdf/format-pdf.ts#L446
So I used that. 

This changes fix the initial issue. 
I am opening this PR to run tests. I don't know if this change will be supported for all output and all type of LaTeX tables. 
Also so that you can review and advice.

### CODE REVIEW

**Comment by cderv** [comment]
It seems like everything is passing ok. I'll add tests for this new addition though

**Comment by jjallaire** [comment]
@cderv LMK when its okay to merge this

**Comment by cderv** [comment]
@jjallaire this is now ok I manage to add the test and check different scenario. @dragonstyle hopefully I put them in the right place, tests for tables in latex using crossrefs can be put in several places in our current organization.

Regarding **gt** support I'll work with Rich to fix a few things in the R package before doing anything else in Quarto. It is not currently working ideally.

**Comment by skywalker1342** [comment]
flextable also had this issue.
when I used flextable to produce PDF format:

---
title: "test"
format: 
  pdf:
    documentclass: ctexrep 
    classoption: 
      - a4paper
      - UTF8
    geometry:
      - top=2.54cm
      - bottom=2.54cm
      - left=3.18cm
      - right=3.18cm
    latex-engine: xelatex
    toc: true
    toc-depth: 3
    keep-tex: true

---


```{r}
#| tbl-cap: "table_example"
iris %>%
  head()  %>% 
  flextable()
```  

 rocessing file: test.qmd
1/2
2/2 [unnamed-chunk-1]
output file: test.knit.md

pandoc 
  to: latex
  output-file: test.tex 
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  block-headings: true
  title: test
  documentclass: ctexrep
  classoption:
    - a4paper
    - UTF8
  geometry:
    - top=2.54cm
    - bottom=2.54cm
    - left=3.18cm
    - right=3.18cm
  latex-engine: xelatex

running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999998 (TeX Live 2026) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages

compilation failed- error
Package array Error:  Illegal pream-token (\caption): `c' used.

See the array package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.280 |p{0.75in}|p{0.75in}|p{0.75in}|p{0.75in}}

**Comment by cderv** [comment]
@skywalker1342 please open a new issue with reproducible example instead of commenting in an old PR.

See also how to format issue correctly https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us

thank you !

**Pull request merged**
