### PR TITLE
tests -Fix Windows issue with LaTeX rendering

### PR DESCRIPTION
**Pull request by cderv**

### CODE REVIEW

**Comment by cderv** [comment]
This is now the error that would be thrown in 
````
    Rendering PDF
    running xelatex - 1
    This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
     restricted \write18 enabled.
    entering extended mode

    updating tlmgr

    updating existing packages
    finding package for sansmath.sty
    > 1 package to install
    > installing sansmath (1 of 1)
    [non-error-thrown] Problem running `fmtutil-sys --all` to rebuild format tree.
````

This is what is happening in our CI. There is an issue with the TinyTeX build for July that we use. Possibly the new build I made will solve it too: https://github.com/rstudio/tinytex-releases/releases/tag/v2024.07.03

This issue with TeX Live version problem was triggered by a Quarto bug itself. We were unable to verify that a CTAN package has correctly been installed, and so we were still trying to install it a second time while it was not needed, and running unnecessary step with fmtutils which takes time. With this fix, we are probably getting some speed on LaTeX rendering. 

Other note: We probably should write more verbose debug logging for all this part.

**Comment by cderv** [comment]
So this fixes the tests. No more issues. 

Do we want to backport in 1.5 ? 

Not that possibly this is transient problem as now `quarto update tinytex` or `quarto install tinytex` should also solve it. 

I am checking this right now.

**Comment by cderv** [comment]
> Not that possibly this is transient problem as now quarto update tinytex or quarto install tinytex should also solve it.
> I am checking this right now.

This is confirmed. I'll re-run the other jobs that should pass now.

**Comment by cderv** [comment]
> Do we want to backport in 1.5 ? I am thinking the part about missing @echo off in the bat file we are creating, which prevent the correct check in verifyPackageInstalled()

That leave us with this question - probably not backporting is ok since an update to TinyTeX fixes it, and the current PR is improvement bugfix to 1.6 (not a regression)

**Comment by cderv** [comment]
> I'll re-run the other jobs that should pass now.

Also confirms that the new TinyTeX bundled fixed most issues.

**Comment by cscheid** [comment]
Let's not backport. It doesn't seem worth breaking our general rule for it.

**Pull request merged**
