### PR TITLE
Correct invalid pattern for http URLs

### LINKED ISSUE #4964: quarto release candidate breaks on an image url
### Bug description

This code renders successfully with Quarto stable

```
---
title: "example of broken link"
---
![](http://r-statistics.co/screenshots/ggplot_masterlist_2.png){width="488"} [SOURCE](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)
```
$ quarto check

[>] Checking Quarto installation......OK
      Version: 1.2.475
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/Users/Apste/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.1/library
      rmarkdown: 2.16

--------------------------------------------------
It does not with the Quarto release candidate. I think it has something to do with 'deno,' whatever that is.

pandoc 
  to: html
  output-file: temp.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: example of broken link
  
ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'C:\Users\Apste\Documents\R Projects\http:\r-statistics.co\screenshots\ggplot_masterlist_2.png'

Error: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'C:\Users\Apste\Documents\R Projects\http:\r-statistics.co\screenshots\ggplot_masterlist_2.png'
    at Object.statSync (deno:runtime/js/30_fs.js:322:9)
    at createWalkEntrySync (file:///C:/PROGRA~1/Quarto/bin/quarto.js:2754:23)
    at expandGlobSync (file:///C:/PROGRA~1/Quarto/bin/quarto.js:2874:25)
    at expandGlobSync.next (<anonymous>)
    at expandGlobs (file:///C:/PROGRA~1/Quarto/bin/quarto.js:5786:24)
    at resolveGlobs (file:///C:/PROGRA~1/Quarto/bin/quarto.js:5862:26)
    at resolvePathGlobs (file:///C:/PROGRA~1/Quarto/bin/quarto.js:5798:12)
    at resolveFileResources (file:///C:/PROGRA~1/Quarto/bin/quarto.js:76176:23)
    at resourceFilesFromFile (file:///C:/PROGRA~1/Quarto/bin/quarto.js:76191:37)
    at resourceFilesFromRenderedFile (file:///C:/PROGRA~1/Quarto/bin/quarto.js:76185:12)

$ quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.290
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/Users/Apste/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.1/library
      knitr: 1.42
      rmarkdown: 2.16

[>] Checking Knitr engine render......OK

RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

### PR DESCRIPTION
**Pull request by dragonstyle**
Both of these patterns are incorrect- they intend to match urls that start with http or https.

Fixes #4964

The LUA resource discovery is a new addition this release, so this represents a regression.

Thanks to @cderv for tracking down this issue!

### CODE REVIEW

**Review by cderv — COMMENTED** [review]
Thank you! Glad I spent time to find this one - rather important ! 

We should probably add a test file with some remote resources (and data uris if not already) ?

**Review by cderv — APPROVED** [review]
And correctly working for me on Windows now!

Thanks !

**Review by cscheid — APPROVED** [review]
Yup, that looks correct to me too.

Should we do a more general review of our patterns to see if we have more instances of `[]` doing unexpected things?

**Comment by cderv** [comment]
> Should we do a more general review of our patterns to see if we have more instances of [] doing unexpected things?

Probably. I did a quick search in VSCODE and I think these are the only one. Double checking is often a good idea!

**Pull request merged**
