### PR TITLE
Rebuild JS script based on YAML references changes

### PR DESCRIPTION
**Pull request by cderv**
Follow up from #2552 which was merged a bit early following @dragonstyle feedback. 

@allenmanning I believe this is needed

### CODE REVIEW

**Comment by cderv** [comment]
🤔 too much line change. Let me check

**Comment by cderv** [comment]
@dragonstyle I ran `quarto build-js` - is this expected to get  some id change to mermaid ?

**Comment by dragonstyle** [comment]
I'm not 100% sure about those other changes (I think they're probably fine / expected)- tagging @cscheid who can confirm.

**Comment by cderv** [comment]
I can just remove them for this PR following #2255. Just that it happens to me, so if we need to change the way to run the script, that is the opportunity. 

Sorry to bother everyone with that 😅

**Comment by cscheid** [comment]
@dragonstyle has it right. The internal IDs don't need to be stable from build to build. They're there to help debug the YAML validation code (they _are_ stable if you don't change the schemas, but are not if you do, so these diffs are expected.)

If they start to get annoying, I'll put the feature behind a flag.

**Comment by cderv** [comment]
Ok great. So this PR is probably good to merge then. right ?

**Pull request merged**
