### PR TITLE
Typst callout without body

### LINKED ISSUE #9763: Typst callout without body
### Bug description

With format Typst, using `::: {.callout-warning appearance="default"}` always returns a box with a colored title and a body, even when there is no body to show.
In html format, with the same code, only the colored title is showed.

### Steps to reproduce

```
---
title: "Test callout"
format: typst

---

::: {.callout-warning appearance="default"}
## Test callout
:::
```

### Actual behavior

image

### Expected behavior

image

### Solution suggested
  
in quarto-cli/src/resources/formats/typst/pandoc/quarto/definitions.typ  
add an if statement in line 165-168

now:
```
      block(
        inset: 1pt, 
        width: 100%, 
        block(fill: white, width: 100%, inset: 8pt, body)))
```

after:
```
      if(body != []){
        block(
          inset: 1pt, 
          width: 100%, 
          block(fill: white, width: 100%, inset: 8pt, body))
      }
    )
```

### PR DESCRIPTION
**Pull request by debdagybra**
See #9763

### CODE REVIEW

**Comment by cscheid** [comment]
Thanks for the PR. Before we can merge, we need you to sign and submit a CLA: https://github.com/quarto-dev/quarto-cli/blob/main/CONTRIBUTING.md

I also would to understand how this works across formats. I believe it works for HTML, but it might have been by accident.

We'd like to at least test:

- html
- revealjs
- pdf
- typst
- docx

**Comment by debdagybra** [comment]
> Before we can merge, we need you to sign and submit a CLA: https://github.com/quarto-dev/quarto-cli/blob/main/CONTRIBUTING.md

Done :)

You were right, the behaviour isn't consistent in all formats

Currently, when the body of the callout is empty:  
- html and revealjs don't show the body part
- pdf (tinytex), typst and docx show an empty body part.

**Comment by cderv** [comment]
Interestingly, same report on revealjs
* https://github.com/quarto-dev/quarto-cli/issues/9821
So we need I guess to extend this PR for good support on all formats.

**Comment by cscheid** [comment]
I'm going to merge this one and start a new issue for tracking all different cases in callouts.

**Comment by cscheid** [comment]
Thanks for the PR, @debdagybra!

**Pull request merged**
